repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [ python ]
        pass_filenames: true
        args: [ '--settings-file', 'backend/.isort.cfg' ]

      - id: black
        name: black
        entry: black
        language: system
        types: [ python ]
        pass_filenames: true
        args: [ '--config', 'backend/pyproject.toml' ]

      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        pass_filenames: false
        args: ['--config', 'backend/.flake8']

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.1
    hooks:
      - id: ruff
        args: [ '--fix', '--config', 'backend/ruff.toml' ]
      - id: ruff-format
