volumes:
  pg_data:
    driver: local

x-base: &base-backend
  build: .
  volumes:
    - .:/code:delegated
  depends_on:
    - db

services:
  backend:
    <<: *base-backend
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=settings.main
    command: >
      sh -c "
      django-admin compilemessages &&
      python manage.py migrate &&
      python apps/common/create_categories/create_olx_categories.py &&
      apps/common/locations/create_regions_and_cities.py &&
      python manage.py runserver 0.0.0.0:8000
      "
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - "pg_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: db_name
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    ports:
      - "5432:5432"
