volumes:
  pg_data:
    driver: local

x-base: &base-backend
  build: .
  volumes:
    - .:/code
  depends_on:
    - db
    - redis

services:
  backend:
    <<: *base-backend
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=settings.main
    entrypoint: ["/code/entrypoint.sh"]
    depends_on:
      - db
      - redis
    restart: unless-stopped
    volumes:
      - .:/code
      - ./logs:/code/logs

  db:
    image: postgres:13
    volumes:
      - "pg_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: db_name
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    ports:
      - "5432:5432"
    restart: unless-stopped
  
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  worker:
    <<: *base-backend
    command: celery -A apps.celery worker --loglevel=info
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - backend
      - redis
    restart: unless-stopped

  daphne:
    <<: *base-backend
    container_name: daphne
    command: bash -c "daphne -v 3 -b 0.0.0.0 -p 8001 apps.asgi:application"
    ports:
      - "8001:8001"
    depends_on:
      - worker
      - backend
      - redis


    volumes:
      - .:/code
      - ./logs:/code/logs
