volumes:
  pg_data:
    driver: local

x-base: &base-backend
  build: .
  volumes:
    - .:/code:delegated
    - ./media:/code/media
  depends_on:
    - db
    - redis

services:
  backend:
    <<: *base-backend
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=settings.main
    command: >
      sh -c "
      django-admin compilemessages &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py create_default_superuser &&
      python manage.py create_regions_and_cities &&
      python manage.py create_currency &&
      python manage.py create_olx_categories &&
      : python manage.py load_fixtures &&
      : python manage.py collectstatic --no-input --clear
      python manage.py runserver 0.0.0.0:8000
      : gunicorn --workers 3 --bind 0.0.0.0:8000 apps.wsgi:application
      "
    depends_on:
      - db
      - redis
    restart: unless-stopped

  db:
    image: postgres:13
    volumes:
      - "pg_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: db_name
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  worker:
    <<: *base-backend
    command: celery -A apps.celery worker --loglevel=info
    depends_on:
      - backend
      - redis
    restart: unless-stopped