# Generated by Django 5.1.6 on 2025-06-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprofile',
            name='phone_numbers',
            field=models.JSONField(
                blank=True,
                db_index=True,
                default=list,
                help_text='You can add multiple phone numbers.',
                null=True,
                verbose_name='Phone numbers',
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_numbers',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='You can add multiple phone numbers.',
                null=True,
                unique=True,
                verbose_name='Phone numbers',
            ),
        ),
    ]
