# Generated by Django 5.1.6 on 2025-05-07 10:11

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'file',
                    models.FileField(
                        help_text='Allowed formats: image/jpeg, image/png, image/gif, image/webp',
                        upload_to='chat_attachments/%Y/%m/%d/',
                        verbose_name='Attachment',
                    ),
                ),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('content_type', models.CharField(max_length=100)),
                (
                    'message',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.message'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
                'ordering': ['message__created_at'],
            },
        ),
    ]
