# Generated by Django 5.1.6 on 2025-02-17 22:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_useractivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name='Create date'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useractivity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Update date'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='first_user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='first_user',
                to=settings.AUTH_USER_MODEL,
                verbose_name='First User',
            ),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='second_user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='second_user',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Second User',
            ),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='last_seen',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Seen'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='activity',
                to=settings.AUTH_USER_MODEL,
                verbose_name='User',
            ),
        ),
    ]
