# Generated by Django 5.1.6 on 2025-05-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(
                blank=True,
                help_text='Allowed formats: image/jpeg, image/png, image/gif, image/webp',
                null=True,
                upload_to='chat_attachments/images/%Y/%m/%d',
                verbose_name='Attachment',
            ),
        ),
    ]
