# Generated by Django 5.1 on 2024-10-30 21:52

import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('name', models.CharField(max_length=100, verbose_name='City')),
                ('name_uk', models.CharField(max_length=100, null=True, verbose_name='City')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='City')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='City')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCity',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Create date')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Update date')),
                ('name', models.CharField(max_length=100, verbose_name='City')),
                ('name_uk', models.CharField(max_length=100, null=True, verbose_name='City')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='City')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='City')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Slug')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                (
                    'history_type',
                    models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
                ),
            ],
            options={
                'verbose_name': 'historical City',
                'verbose_name_plural': 'historical Cities',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRegion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Create date')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Update date')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Region')),
                ('name_uk', models.CharField(max_length=100, null=True, unique=True, verbose_name='Region')),
                ('name_en', models.CharField(max_length=100, null=True, unique=True, verbose_name='Region')),
                ('name_ru', models.CharField(max_length=100, null=True, unique=True, verbose_name='Region')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Slug')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                (
                    'history_type',
                    models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
                ),
            ],
            options={
                'verbose_name': 'historical Region',
                'verbose_name_plural': 'historical Regions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                (
                    'location_type',
                    models.CharField(
                        choices=[('city', 'City'), ('village', 'Village')],
                        help_text='Type of location',
                        max_length=20,
                        verbose_name='Location Type',
                    ),
                ),
                (
                    'latitude',
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
                ),
                (
                    'longitude',
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'
                    ),
                ),
                (
                    'location_name',
                    models.CharField(
                        blank=True, default='-', editable=False, max_length=255, verbose_name='Location name'
                    ),
                ),
                (
                    'region_name',
                    models.CharField(
                        blank=True, default='-', editable=False, max_length=255, verbose_name='Region name'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Region')),
                ('name_uk', models.CharField(max_length=100, null=True, unique=True, verbose_name='Region')),
                ('name_en', models.CharField(max_length=100, null=True, unique=True, verbose_name='Region')),
                ('name_ru', models.CharField(max_length=100, null=True, unique=True, verbose_name='Region')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'db_table': 'regions',
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('name', models.CharField(max_length=100, verbose_name='Village Name')),
            ],
            options={
                'verbose_name': 'Village',
                'verbose_name_plural': 'Villages',
                'db_table': 'village',
            },
        ),
    ]
