# Generated by Django 5.1 on 2024-10-13 20:50

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Region')),
                ('name_uk', models.CharField(max_length=100, null=True, unique=True, verbose_name='Region')),
                ('name_en', models.CharField(max_length=100, null=True, unique=True, verbose_name='Region')),
                ('name_ru', models.CharField(max_length=100, null=True, unique=True, verbose_name='Region')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'db_table': 'regions',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('name', models.CharField(max_length=100, verbose_name='City')),
                ('name_uk', models.CharField(max_length=100, null=True, verbose_name='City')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='City')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='City')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Slug')),
                (
                    'region',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='locations.region'
                    ),
                ),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'db_table': 'city',
                'unique_together': {('name', 'region')},
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('name', models.CharField(max_length=100, verbose_name='Village Name')),
                (
                    'region',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='locations.region'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Village',
                'verbose_name_plural': 'Villages',
                'db_table': 'village',
                'unique_together': {('name', 'region')},
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                (
                    'location_type',
                    models.CharField(
                        choices=[('city', 'City'), ('village', 'Village')], max_length=20, verbose_name='Location Type'
                    ),
                ),
                (
                    'latitude',
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
                ),
                (
                    'longitude',
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'
                    ),
                ),
                (
                    'city',
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.city'
                    ),
                ),
                (
                    'village',
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.village'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'db_table': 'location',
                'unique_together': {('latitude', 'longitude')},
            },
        ),
    ]
