# Generated by Django 5.1.6 on 2025-05-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='UserLeadsFromElectronInk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('email', models.CharField(max_length=255, verbose_name='email')),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'electron_ink_table',
            },
        ),
    ]
