# Generated by Django 5.1 on 2024-09-10 14:34

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Filter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create date"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update date"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("checkbox", "Checkbox"),
                            ("checkboxes", "Checkboxes"),
                            ("select", "Select"),
                            ("input", "Input"),
                            ("salary", "Salary"),
                            ("price", "Price"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "label",
                    models.CharField(max_length=255, verbose_name="Label"),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Unit",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Scope",
                    ),
                ),
            ],
            options={
                "verbose_name": "Filter",
                "verbose_name_plural": "Filters",
                "db_table": "filters",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create date"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update date"),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Category name"),
                ),
                (
                    "title_uk",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Category name"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Category name"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Category name"
                    ),
                ),
                (
                    "img",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="categories",
                        verbose_name="Image",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="products.category",
                        verbose_name="Parent category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "db_table": "category",
                "unique_together": {("title", "parent")},
            },
        ),
        migrations.CreateModel(
            name="FilterOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(blank=True, null=True, verbose_name="Order"),
                ),
                (
                    "ranges",
                    models.JSONField(blank=True, null=True, verbose_name="Ranges"),
                ),
                (
                    "constraints",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("integer", "Integer"),
                            ("float", "Float"),
                            ("bool", "Boolean"),
                        ],
                        max_length=20,
                        verbose_name="Constraint type",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="filter_options", to="products.category"
                    ),
                ),
                (
                    "filter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="products.filter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FilterValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(max_length=255, verbose_name="label"),
                ),
                (
                    "value",
                    models.CharField(max_length=100, verbose_name="Value"),
                ),
                (
                    "filter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="products.filter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Filter value",
                "verbose_name_plural": "Filter values",
                "db_table": "filter_values",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create date"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update date"),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Product name"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.0"),
                                message="Must be greater than or equal to 0.0.",
                            )
                        ],
                        verbose_name="Price",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Product description"),
                ),
                (
                    "characteristics",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Characteristics"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="category_products",
                        to="products.category",
                        verbose_name="Category",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_sellers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Seller",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "db_table": "product",
                "unique_together": {("title", "seller")},
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/%Y/%m/%d",
                        verbose_name="Image",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_images",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Image",
                "verbose_name_plural": "Product Images",
                "db_table": "product_image",
            },
        ),
    ]
