# Generated by Django 5.1 on 2024-10-30 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalcategory',
            name='history_user',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='historicalcategory',
            name='parent',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='products.category',
                verbose_name='Parent category',
            ),
        ),
        migrations.AddField(
            model_name='historicalcurrency',
            name='history_user',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='historicalprice',
            name='currency',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='products.currency',
                verbose_name='Currency',
            ),
        ),
        migrations.AddField(
            model_name='historicalprice',
            name='history_user',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='category',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='products.category',
                verbose_name='Category',
            ),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='history_user',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='seller',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Seller',
            ),
        ),
        migrations.AddField(
            model_name='historicalproductimage',
            name='history_user',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='historicalproductvideo',
            name='history_user',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='price',
            name='currency',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='products.currency', verbose_name='Currency'
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='products',
                to='products.category',
                verbose_name='Category',
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='seller_products',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Seller',
            ),
        ),
        migrations.AddField(
            model_name='price',
            name='product',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='prices',
                to='products.product',
                verbose_name='Product',
            ),
        ),
        migrations.AddField(
            model_name='historicalproductvideo',
            name='product',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='products.product',
            ),
        ),
        migrations.AddField(
            model_name='historicalproductimage',
            name='product',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='products.product',
            ),
        ),
        migrations.AddField(
            model_name='historicalprice',
            name='product',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='products.product',
                verbose_name='Product',
            ),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='products.product'
            ),
        ),
        migrations.AddField(
            model_name='productvideo',
            name='product',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='product_videos', to='products.product'
            ),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('title', 'parent', 'cat_id_olx')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('title', 'seller', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('product', 'currency')},
        ),
    ]
