# Generated by Django 5.1 on 2025-02-06 19:15

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='description',
            field=models.TextField(
                validators=[
                    django.core.validators.MinLengthValidator(10, message='Product description is too short'),
                    django.core.validators.MaxLengthValidator(10000, message='Product description is too long'),
                ],
                verbose_name='Product description',
            ),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='status',
            field=models.CharField(
                choices=[('new', 'New'), ('used', 'Used')],
                default='used',
                help_text='Indicates the condition of the product. Select `New` for new items and `Used` for used ones.',
                max_length=20,
                verbose_name='Status',
            ),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(
                validators=[
                    django.core.validators.MinLengthValidator(10, message='Product description is too short'),
                    django.core.validators.MaxLengthValidator(10000, message='Product description is too long'),
                ],
                verbose_name='Product description',
            ),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(
                choices=[('new', 'New'), ('used', 'Used')],
                default='used',
                help_text='Indicates the condition of the product. Select `New` for new items and `Used` for used ones.',
                max_length=20,
                verbose_name='Status',
            ),
        ),
    ]
