# Generated by Django 5.1 on 2025-02-04 20:14

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproductimage',
            name='image',
            field=models.TextField(
                blank=True,
                help_text='Allowed image formats: image/jpeg, image/png, image/gif, image/webp',
                max_length=100,
                null=True,
                verbose_name='Image',
            ),
        ),
        migrations.AlterField(
            model_name='historicalproductvideo',
            name='video',
            field=models.TextField(
                blank=True,
                help_text='Allowed video formats: video/mp4, video/x-m4v, video/quicktime, video/x-msvideo, video/x-ms-wmv, video/wmv, video/x-flv, video/flv, video/x-matroska, video/mkv, video/webm, video/ogg',
                max_length=100,
                null=True,
                verbose_name='Video',
            ),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(
                blank=True,
                help_text='Allowed image formats: image/jpeg, image/png, image/gif, image/webp',
                null=True,
                upload_to='products/images/%Y/%m/%d',
                verbose_name='Image',
            ),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='video',
            field=models.FileField(
                blank=True,
                help_text='Allowed video formats: video/mp4, video/x-m4v, video/quicktime, video/x-msvideo, video/x-ms-wmv, video/wmv, video/x-flv, video/flv, video/x-matroska, video/mkv, video/webm, video/ogg',
                null=True,
                upload_to='products/videos/%Y/%m/%d',
                verbose_name='Video',
            ),
        ),
    ]
