# Generated by Django 5.1.6 on 2025-02-14 23:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_historicalproductimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='description',
            field=models.TextField(
                validators=[
                    django.core.validators.MinLengthValidator(10, message='Product description is too short'),
                    django.core.validators.MaxLengthValidator(10000, message='Product description is too long'),
                ],
                verbose_name='Product description',
            ),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='status',
            field=models.CharField(
                choices=[('new', 'New'), ('used', 'Used')],
                default='used',
                help_text='Indicates the condition of the product. Select `New` for new items and `Used` for used ones.',
                max_length=20,
                verbose_name='Status',
            ),
        ),
        migrations.AlterField(
            model_name='historicalproductimage',
            name='image',
            field=models.TextField(
                blank=True,
                default='examples/product_empty_image.jpg',
                help_text='Дозволені формати зображень: image/jpeg, image/png, image/gif, image/webp',
                max_length=100,
                null=True,
                verbose_name='Image',
            ),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(
                validators=[
                    django.core.validators.MinLengthValidator(10, message='Product description is too short'),
                    django.core.validators.MaxLengthValidator(10000, message='Product description is too long'),
                ],
                verbose_name='Product description',
            ),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(
                choices=[('new', 'New'), ('used', 'Used')],
                default='used',
                help_text='Indicates the condition of the product. Select `New` for new items and `Used` for used ones.',
                max_length=20,
                verbose_name='Status',
            ),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(
                blank=True,
                default='examples/product_empty_image.jpg',
                help_text='Дозволені формати зображень: image/jpeg, image/png, image/gif, image/webp',
                null=True,
                upload_to='products/images/%Y/%m/%d',
                verbose_name='Image',
            ),
        ),
    ]
