# Generated by Django 5.1.6 on 2025-02-21 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_product_title_9e36ed_idx'),
        ('products', '0005_alter_historicalproduct_description_and_more'),
    ]

    operations = []
