# Generated by Django 5.1.6 on 2025-02-22 19:10

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_merge_20250221_1739'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='publication_status',
            field=models.CharField(
                choices=[
                    ('active', 'Active'),
                    ('inactive', 'Inactive'),
                    ('draft', 'Draft'),
                    ('rejected', 'Rejected'),
                    ('sold', 'Sold'),
                    ('deleted', 'Deleted'),
                ],
                default='draft',
                help_text='Defines the visibility of the product. Select `Active` to make the product publicly available, `Draft` for unpublished items under review, or `Rejected` for products that are not approved.',
                max_length=20,
                verbose_name='Publication status',
            ),
        ),
        migrations.AlterField(
            model_name='product',
            name='publication_status',
            field=models.CharField(
                choices=[
                    ('active', 'Active'),
                    ('inactive', 'Inactive'),
                    ('draft', 'Draft'),
                    ('rejected', 'Rejected'),
                    ('sold', 'Sold'),
                    ('deleted', 'Deleted'),
                ],
                default='draft',
                help_text='Defines the visibility of the product. Select `Active` to make the product publicly available, `Draft` for unpublished items under review, or `Rejected` for products that are not approved.',
                max_length=20,
                verbose_name='Publication status',
            ),
        ),
        migrations.CreateModel(
            name='HistoricalProductDeactivationFeedback',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Create date')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Update date')),
                (
                    'answer',
                    models.CharField(
                        choices=[('sold', 'Sold'), ('sold_elsewhere', 'Sold Elsewhere'), ('not_sold', 'Not Sold')],
                        default='sold',
                        help_text='The current sale status of the deactivated product.',
                        max_length=20,
                        verbose_name='Sale Status',
                    ),
                ),
                (
                    'description',
                    models.TextField(
                        blank=True,
                        help_text='Description of why the product was deactivated, including the reason and any additional comments.',
                        null=True,
                        verbose_name='Deactivation Reason',
                    ),
                ),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                (
                    'history_type',
                    models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
                ),
                (
                    'history_user',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'product',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text='The product that has been deactivated.',
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='products.product',
                        verbose_name='Product',
                    ),
                ),
            ],
            options={
                'verbose_name': 'historical Deactivated Product',
                'verbose_name_plural': 'historical Deactivated Products',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProductDeactivationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                (
                    'answer',
                    models.CharField(
                        choices=[('sold', 'Sold'), ('sold_elsewhere', 'Sold Elsewhere'), ('not_sold', 'Not Sold')],
                        default='sold',
                        help_text='The current sale status of the deactivated product.',
                        max_length=20,
                        verbose_name='Sale Status',
                    ),
                ),
                (
                    'description',
                    models.TextField(
                        blank=True,
                        help_text='Description of why the product was deactivated, including the reason and any additional comments.',
                        null=True,
                        verbose_name='Deactivation Reason',
                    ),
                ),
                (
                    'product',
                    models.ForeignKey(
                        help_text='The product that has been deactivated.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='deactivated_product',
                        to='products.product',
                        verbose_name='Product',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Deactivated Product',
                'verbose_name_plural': 'Deactivated Products',
                'db_table': 'deactivated_products',
            },
        ),
    ]
