# Generated by Django 5.1.6 on 2025-02-23 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_historicalproduct_publication_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalproductdeactivationfeedback',
            options={
                'get_latest_by': ('history_date', 'history_id'),
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical Product Deactivation Feedback',
                'verbose_name_plural': 'historical Product Deactivation Feedbacks',
            },
        ),
        migrations.AlterModelOptions(
            name='productdeactivationfeedback',
            options={
                'verbose_name': 'Product Deactivation Feedback',
                'verbose_name_plural': 'Product Deactivation Feedbacks',
            },
        ),
        migrations.AlterModelTable(
            name='productdeactivationfeedback',
            table='product_deactivation_feedbacks',
        ),
    ]
