# Generated by Django 5.1.6 on 2025-02-23 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_historicalproductdeactivationfeedback_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalproductdeactivationfeedback',
            options={
                'get_latest_by': ('history_date', 'history_id'),
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical Deactivation Feedback',
                'verbose_name_plural': 'historical Deactivation Feedbacks',
            },
        ),
        migrations.AlterModelOptions(
            name='productdeactivationfeedback',
            options={'verbose_name': 'Deactivation Feedback', 'verbose_name_plural': 'Deactivation Feedbacks'},
        ),
        migrations.AlterModelTable(
            name='productdeactivationfeedback',
            table='deactivation_feedbacks',
        ),
    ]
