cities = {
    'Вінницька область': [
        {
            'name': 'Бар',
            'latitude': 49.07806,
            'longitude': 27.68306,
            'languages': {'uk': 'Бар', 'en': 'Bar', 'ru': 'Бар'},
        },
        {
            'name': 'Бершадь',
            'latitude': 48.37278,
            'longitude': 29.5325,
            'languages': {'uk': 'Бершадь', 'en': 'Bershad', 'ru': 'Бершадь'},
        },
        {
            'name': 'Вінниця',
            'latitude': 49.23722,
            'longitude': 28.46722,
            'languages': {'uk': 'Вінниця', 'en': 'Vinnytsia', 'ru': 'Винница'},
        },
        {
            'name': 'Гайсин',
            'latitude': 48.81028,
            'longitude': 29.38417,
            'languages': {'uk': 'Гайсин', 'en': 'Haisyn', 'ru': 'Гайсин'},
        },
        {
            'name': 'Гнівань',
            'latitude': 49.09111,
            'longitude': 28.34861,
            'languages': {'uk': 'Гнівань', 'en': 'Hnivan', 'ru': 'Гнивань'},
        },
        {
            'name': 'Жмеринка',
            'latitude': 49.03694,
            'longitude': 28.10361,
            'languages': {'uk': 'Жмеринка', 'en': 'Zhmerynka', 'ru': 'Жмеринка'},
        },
        {
            'name': 'Іллінці',
            'latitude': 49.10528,
            'longitude': 29.20806,
            'languages': {'uk': 'Іллінці', 'en': 'Illintsi', 'ru': 'Ильинцы'},
        },
        {
            'name': 'Калинівка',
            'latitude': 49.44722,
            'longitude': 28.52306,
            'languages': {'uk': 'Калинівка', 'en': 'Kalynivka', 'ru': 'Калиновка'},
        },
        {
            'name': 'Козятин',
            'latitude': 49.71667,
            'longitude': 28.83333,
            'languages': {'uk': 'Козятин', 'en': 'Koziatyn', 'ru': 'Казатин'},
        },
        {
            'name': 'Ладижин',
            'latitude': 48.68972,
            'longitude': 29.24167,
            'languages': {'uk': 'Ладижин', 'en': 'Ladyzhyn', 'ru': 'Ладыжин'},
        },
        {
            'name': 'Липовець',
            'latitude': 49.21611,
            'longitude': 29.05611,
            'languages': {'uk': 'Липовець', 'en': 'Lypovets', 'ru': 'Липовец'},
        },
        {
            'name': 'Могилів',
            'latitude': 48.455,
            'longitude': 27.80806,
            'languages': {'uk': 'Могилів', 'en': 'Mohyliv', 'ru': 'Могилев'},
        },
        {
            'name': 'Немирів',
            'latitude': 48.97944,
            'longitude': 28.84389,
            'languages': {'uk': 'Немирів', 'en': 'Nemyriv', 'ru': 'Немиров'},
        },
        {
            'name': 'Погребище',
            'latitude': 49.48694,
            'longitude': 29.27333,
            'languages': {'uk': 'Погребище', 'en': 'Pohrebyshche', 'ru': 'Погребище'},
        },
        {
            'name': 'Тульчин',
            'latitude': 48.67444,
            'longitude': 28.84972,
            'languages': {'uk': 'Тульчин', 'en': 'Tulchyn', 'ru': 'Тульчин'},
        },
        {
            'name': 'Хмільник',
            'latitude': 49.55694,
            'longitude': 27.95722,
            'languages': {'uk': 'Хмільник', 'en': 'Khmilnyk', 'ru': 'Хмельник'},
        },
        {
            'name': 'Шаргород',
            'latitude': 48.75528,
            'longitude': 28.07889,
            'languages': {'uk': 'Шаргород', 'en': 'Sharhorod', 'ru': 'Шаргород'},
        },
        {
            'name': 'Ямпіль',
            'latitude': 48.245,
            'longitude': 28.27778,
            'languages': {'uk': 'Ямпіль', 'en': 'Yampil', 'ru': 'Ямполь'},
        },
    ],
    'Волинська область': [
        {
            'name': 'Берестечко',
            'latitude': 50.357222,
            'longitude': 25.112222,
            'languages': {'uk': 'Берестечко', 'en': 'Berestechko', 'ru': 'Берестечко'},
        },
        {
            'name': 'Володимир-Волинський',
            'latitude': 50.841389,
            'longitude': 24.322222,
            'languages': {'uk': 'Володимир-Волинський', 'en': 'Volodymyr-Volynskyi', 'ru': 'Владимир-Волынский'},
        },
        {
            'name': 'Горохів',
            'latitude': 50.499444,
            'longitude': 24.765000,
            'languages': {'uk': 'Горохів', 'en': 'Horokhiv', 'ru': 'Горохов'},
        },
        {
            'name': 'Камінь-Каширський',
            'latitude': 51.620000,
            'longitude': 24.965278,
            'languages': {'uk': 'Камінь-Каширський', 'en': 'Kamin-Kashyrskyi', 'ru': 'Камень-Каширский'},
        },
        {
            'name': 'Ківерці',
            'latitude': 50.833056,
            'longitude': 25.461389,
            'languages': {'uk': 'Ківерці', 'en': 'Kivertsi', 'ru': 'Киверцы'},
        },
        {
            'name': 'Ковель',
            'latitude': 51.219167,
            'longitude': 24.687222,
            'languages': {'uk': 'Ковель', 'en': 'Kovel', 'ru': 'Ковель'},
        },
        {
            'name': 'Луцьк',
            'latitude': 50.748889,
            'longitude': 25.324444,
            'languages': {'uk': 'Луцьк', 'en': 'Lutsk', 'ru': 'Луцк'},
        },
        {
            'name': 'Любомль',
            'latitude': 51.223611,
            'longitude': 24.032778,
            'languages': {'uk': 'Любомль', 'en': 'Liuboml', 'ru': 'Любомль'},
        },
        {
            'name': 'Нововолинськ',
            'latitude': 50.727222,
            'longitude': 24.165000,
            'languages': {'uk': 'Нововолинськ', 'en': 'Novovolynsk', 'ru': 'Нововолынск'},
        },
        {
            'name': 'Рожище',
            'latitude': 50.912778,
            'longitude': 25.270000,
            'languages': {'uk': 'Рожище', 'en': 'Rozhyshche', 'ru': 'Рожище'},
        },
        {
            'name': 'Устилуг',
            'latitude': 50.860000,
            'longitude': 24.156944,
            'languages': {'uk': 'Устилуг', 'en': 'Ustyluh', 'ru': 'Устилуг'},
        },
    ],
    'Дніпропетровська область': [
        {
            'name': 'Апостолове',
            'latitude': 47.659444,
            'longitude': 33.716667,
            'languages': {'uk': 'Апостолове', 'en': 'Apostolove', 'ru': 'Апостолово'},
        },
        {
            'name': 'Верхівцеве',
            'latitude': 48.485278,
            'longitude': 34.254444,
            'languages': {'uk': 'Верхівцеве', 'en': 'Verkhivtseve', 'ru': 'Верховцево'},
        },
        {
            'name': 'Верхньодніпровськ',
            'latitude': 48.642500,
            'longitude': 34.340278,
            'languages': {'uk': 'Верхньодніпровськ', 'en': 'Verkhnodniprovsk', 'ru': 'Верхнеднепровск'},
        },
        {
            'name': 'Вільногірськ',
            'latitude': 48.478056,
            'longitude': 34.028056,
            'languages': {'uk': 'Вільногірськ', 'en': 'Vilnohirsk', 'ru': 'Вольногорск'},
        },
        {
            'name': 'Дніпро',
            'latitude': 48.466111,
            'longitude': 35.025278,
            'languages': {'uk': 'Дніпро', 'en': 'Dnipro', 'ru': 'Днепр'},
        },
        {
            'name': 'Жовті Води',
            'latitude': 48.366389,
            'longitude': 33.502500,
            'languages': {'uk': 'Жовті Води', 'en': 'Zhovti Vody', 'ru': 'Желтые Воды'},
        },
        {
            'name': 'Зеленодольськ',
            'latitude': 47.566389,
            'longitude': 33.646389,
            'languages': {'uk': 'Зеленодольськ', 'en': 'Zelenodolsk', 'ru': 'Зеленодольск'},
        },
        {
            'name': 'Кам\'янське',
            'latitude': 48.528889,
            'longitude': 34.597222,
            'languages': {'uk': 'Кам\'янське', 'en': 'Kamianske', 'ru': 'Каменское'},
        },
        {
            'name': 'Кривий Ріг',
            'latitude': 47.908611,
            'longitude': 33.348889,
            'languages': {'uk': 'Кривий Ріг', 'en': 'Kryvyi Rih', 'ru': 'Кривой Рог'},
        },
        {
            'name': 'Марганець',
            'latitude': 47.644722,
            'longitude': 34.604167,
            'languages': {'uk': 'Марганець', 'en': 'Marhanets', 'ru': 'Марганец'},
        },
        {
            'name': 'Нікополь',
            'latitude': 47.577222,
            'longitude': 34.357500,
            'languages': {'uk': 'Нікополь', 'en': 'Nikopol', 'ru': 'Никополь'},
        },
        {
            'name': 'Новомосковськ',
            'latitude': 48.637778,
            'longitude': 35.228889,
            'languages': {'uk': 'Новомосковськ', 'en': 'Novomoskovsk', 'ru': 'Новомосковск'},
        },
        {
            'name': 'Павлоград',
            'latitude': 48.520000,
            'longitude': 35.870000,
            'languages': {'uk': 'Павлоград', 'en': 'Pavlohrad', 'ru': 'Павлоград'},
        },
        {
            'name': 'Перещепине',
            'latitude': 49.014444,
            'longitude': 35.365000,
            'languages': {'uk': 'Перещепине', 'en': 'Pereshchepyne', 'ru': 'Перещепино'},
        },
        {
            'name': 'Першотравенськ',
            'latitude': 48.347500,
            'longitude': 36.401667,
            'languages': {'uk': 'Першотравенськ', 'en': 'Pershotravensk', 'ru': 'Першотравенск'},
        },
        {
            'name': 'Підгородне',
            'latitude': 48.575000,
            'longitude': 35.102222,
            'languages': {'uk': 'Підгородне', 'en': 'Pidhorodne', 'ru': 'Подгородное'},
        },
        {
            'name': 'П\'ятихатки',
            'latitude': 48.413056,
            'longitude': 33.702778,
            'languages': {'uk': 'П\'ятихатки', 'en': 'Piatykhatky', 'ru': 'Пятихатки'},
        },
        {
            'name': 'Покров',
            'latitude': 47.653333,
            'longitude': 34.084167,
            'languages': {'uk': 'Покров', 'en': 'Pokrov', 'ru': 'Покров'},
        },
        {
            'name': 'Синельникове',
            'latitude': 48.317222,
            'longitude': 35.511944,
            'languages': {'uk': 'Синельникове', 'en': 'Synelnykove', 'ru': 'Синельниково'},
        },
        {
            'name': 'Тернівка',
            'latitude': 48.524444,
            'longitude': 36.082500,
            'languages': {'uk': 'Тернівка', 'en': 'Ternivka', 'ru': 'Терновка'},
        },
    ],
    'Донецька область': [
        {
            'name': 'Авдіївка',
            'latitude': 48.0205,
            'longitude': 37.6525,
            'languages': {'uk': 'Авдіївка', 'en': 'Avdiivka', 'ru': 'Авдеевка'},
        },
        {
            'name': 'Бахмут',
            'latitude': 48.5788,
            'longitude': 38.0463,
            'languages': {'uk': 'Бахмут', 'en': 'Bakhmut', 'ru': 'Бахмут'},
        },
        {
            'name': 'Вугледар',
            'latitude': 48.3341,
            'longitude': 37.7104,
            'languages': {'uk': 'Вугледар', 'en': 'Vuhledar', 'ru': 'Угледар'},
        },
        {
            'name': 'Горлівка',
            'latitude': 48.2985,
            'longitude': 38.0382,
            'languages': {'uk': 'Горлівка', 'en': 'Horlivka', 'ru': 'Горловка'},
        },
        {
            'name': 'Дебальцеве',
            'latitude': 48.3173,
            'longitude': 38.3869,
            'languages': {'uk': 'Дебальцеве', 'en': 'Debaltseve', 'ru': 'Дебальцево'},
        },
        {
            'name': 'Торецьк',
            'latitude': 48.6758,
            'longitude': 38.4453,
            'languages': {'uk': 'Торецьк', 'en': 'Toretsk', 'ru': 'Торецк'},
        },
        {
            'name': 'Мирноград',
            'latitude': 48.3894,
            'longitude': 37.5234,
            'languages': {'uk': 'Мирноград', 'en': 'Myrnohrad', 'ru': 'Мирноград'},
        },
        {
            'name': 'Добропілля',
            'latitude': 48.3021,
            'longitude': 37.3884,
            'languages': {'uk': 'Добропілля', 'en': 'Dobropillia', 'ru': 'Доброполье'},
        },
        {
            'name': 'Докучаєвськ',
            'latitude': 48.1203,
            'longitude': 37.5394,
            'languages': {'uk': 'Докучаєвськ', 'en': 'Dokuchaievsk', 'ru': 'Докучаевск'},
        },
        {
            'name': 'Донецьк',
            'latitude': 48.0159,
            'longitude': 37.8029,
            'languages': {'uk': 'Донецьк', 'en': 'Donetsk', 'ru': 'Донецк'},
        },
        {
            'name': 'Дружківка',
            'latitude': 48.6872,
            'longitude': 37.1770,
            'languages': {'uk': 'Дружківка', 'en': 'Druzhkivka', 'ru': 'Дружковка'},
        },
        {
            'name': 'Єнакієве',
            'latitude': 48.0286,
            'longitude': 38.4747,
            'languages': {'uk': 'Єнакієве', 'en': 'Yenakiieve', 'ru': 'Енакиево'},
        },
        {
            'name': 'Жданівка',
            'latitude': 48.1377,
            'longitude': 38.0135,
            'languages': {'uk': 'Жданівка', 'en': 'Zhdanivka', 'ru': 'Ждановка'},
        },
        {
            'name': 'Хрестівка',
            'latitude': 48.3836,
            'longitude': 38.5356,
            'languages': {'uk': 'Хрестівка', 'en': 'Khrestivka', 'ru': 'Хрестовка'},
        },
        {
            'name': 'Костянтинівка',
            'latitude': 48.7760,
            'longitude': 37.6401,
            'languages': {'uk': 'Костянтинівка', 'en': 'Kostiantynivka', 'ru': 'Константиновка'},
        },
        {
            'name': 'Краматорськ',
            'latitude': 48.7075,
            'longitude': 37.5895,
            'languages': {'uk': 'Краматорськ', 'en': 'Kramatorsk', 'ru': 'Краматорск'},
        },
        {
            'name': 'Лиман',
            'latitude': 48.7507,
            'longitude': 37.7300,
            'languages': {'uk': 'Лиман', 'en': 'Lyman', 'ru': 'Лиман'},
        },
        {
            'name': 'Покровськ',
            'latitude': 48.3103,
            'longitude': 37.5186,
            'languages': {'uk': 'Покровськ', 'en': 'Pokrovsk', 'ru': 'Покровск'},
        },
        {
            'name': 'Макіївка',
            'latitude': 48.0263,
            'longitude': 37.9633,
            'languages': {'uk': 'Макіївка', 'en': 'Makiivka', 'ru': 'Макеевка'},
        },
        {
            'name': 'Маріуполь',
            'latitude': 47.0971,
            'longitude': 37.5435,
            'languages': {'uk': 'Маріуполь', 'en': 'Mariupol', 'ru': 'Мариуполь'},
        },
        {
            'name': 'Новогродівка',
            'latitude': 48.4691,
            'longitude': 37.6867,
            'languages': {'uk': 'Новогродівка', 'en': 'Novohrodivka', 'ru': 'Новогродовка'},
        },
        {
            'name': 'Селидове',
            'latitude': 48.0211,
            'longitude': 37.5965,
            'languages': {'uk': 'Селидове', 'en': 'Selydove', 'ru': 'Селидово'},
        },
        {
            'name': 'Слов\'янськ',
            'latitude': 48.8724,
            'longitude': 37.6172,
            'languages': {'uk': 'Слов\'янськ', 'en': 'Sloviansk', 'ru': 'Славянск'},
        },
        {
            'name': 'Сніжне',
            'latitude': 48.0133,
            'longitude': 38.2241,
            'languages': {'uk': 'Сніжне', 'en': 'Snizhne', 'ru': 'Снежное'},
        },
        {
            'name': 'Чистякове',
            'latitude': 48.1930,
            'longitude': 38.0389,
            'languages': {'uk': 'Чистякове', 'en': 'Chystiakove', 'ru': 'Чистяково'},
        },
        {
            'name': 'Харцизьк',
            'latitude': 48.0606,
            'longitude': 38.0249,
            'languages': {'uk': 'Харцизьк', 'en': 'Khartsyzk', 'ru': 'Харцызск'},
        },
        {
            'name': 'Шахтарськ',
            'latitude': 48.1021,
            'longitude': 38.1117,
            'languages': {'uk': 'Шахтарськ', 'en': 'Shakhtarsk', 'ru': 'Шахтерск'},
        },
        {
            'name': 'Ясинувата',
            'latitude': 48.0614,
            'longitude': 37.7751,
            'languages': {'uk': 'Ясинувата', 'en': 'Yasynuvata', 'ru': 'Ясиноватая'},
        },
    ],
    'Житомирська область': [
        {
            'name': 'Житомир',
            'latitude': 50.2500,
            'longitude': 28.6624,
            'languages': {'uk': 'Житомир', 'en': 'Zhytomyr', 'ru': 'Житомир'},
        },
        {
            'name': 'Бердичів',
            'latitude': 49.8969,
            'longitude': 28.5819,
            'languages': {'uk': 'Бердичів', 'en': 'Berdiansk', 'ru': 'Бердичев'},
        },
        {
            'name': 'Коростень',
            'latitude': 50.9827,
            'longitude': 28.5931,
            'languages': {'uk': 'Коростень', 'en': 'Korosten', 'ru': 'Коростень'},
        },
        {
            'name': 'Новоград-Волинський',
            'latitude': 50.5234,
            'longitude': 27.6140,
            'languages': {'uk': 'Новоград-Волинський', 'en': 'Novograd-Volynskyi', 'ru': 'Новоград-Волынский'},
        },
        {
            'name': 'Малин',
            'latitude': 50.5820,
            'longitude': 28.5977,
            'languages': {'uk': 'Малин', 'en': 'Malyn', 'ru': 'Малин'},
        },
        {
            'name': 'Овруч',
            'latitude': 51.1400,
            'longitude': 28.7922,
            'languages': {'uk': 'Овруч', 'en': 'Ovruch', 'ru': 'Овруч'},
        },
        {
            'name': 'Радомишль',
            'latitude': 50.5483,
            'longitude': 29.0616,
            'languages': {'uk': 'Радомишль', 'en': 'Radomyshl', 'ru': 'Радомышль'},
        },
        {
            'name': 'Чуднів',
            'latitude': 50.3982,
            'longitude': 28.8786,
            'languages': {'uk': 'Чуднів', 'en': 'Chudniv', 'ru': 'Чуднов'},
        },
        {
            'name': 'Андрушівка',
            'latitude': 50.2406,
            'longitude': 28.5628,
            'languages': {'uk': 'Андрушівка', 'en': 'Andrushivka', 'ru': 'Андрушевка'},
        },
        {
            'name': 'Пулин',
            'latitude': 50.5251,
            'longitude': 28.4186,
            'languages': {'uk': 'Пулин', 'en': 'Pulin', 'ru': 'Пулин'},
        },
        {
            'name': 'Баранівка',
            'latitude': 50.4861,
            'longitude': 28.9693,
            'languages': {'uk': 'Баранівка', 'en': 'Baranivka', 'ru': 'Барановка'},
        },
        {
            'name': 'Лугини',
            'latitude': 50.9422,
            'longitude': 28.3653,
            'languages': {'uk': 'Лугини', 'en': 'Luhyny', 'ru': 'Лугины'},
        },
        {
            'name': 'Романів',
            'latitude': 50.2989,
            'longitude': 28.9727,
            'languages': {'uk': 'Романів', 'en': 'Romanyv', 'ru': 'Романов'},
        },
        {
            'name': 'Черняхів',
            'latitude': 50.5358,
            'longitude': 28.4286,
            'languages': {'uk': 'Черняхів', 'en': 'Chernyakhiv', 'ru': 'Чернягов'},
        },
    ],
    'Закарпатська область': [
        {
            'name': 'Берегове',
            'latitude': 48.2025,
            'longitude': 22.6375,
            'languages': {'uk': 'Берегове', 'en': 'Berehove', 'ru': 'Берегово'},
        },
        {
            'name': 'Виноградів',
            'latitude': 48.1497,
            'longitude': 23.0258,
            'languages': {'uk': 'Виноградів', 'en': 'Vynohradiv', 'ru': 'Виноградов'},
        },
        {
            'name': 'Дийда',
            'latitude': 48.2900,
            'longitude': 22.6510,
            'languages': {'uk': 'Дийда', 'en': 'Diyda', 'ru': 'Дийда'},
        },
        {
            'name': 'Іршава',
            'latitude': 48.3172,
            'longitude': 23.0375,
            'languages': {'uk': 'Іршава', 'en': 'Irshava', 'ru': 'Иршава'},
        },
        {
            'name': 'Мукачево',
            'latitude': 48.4497,
            'longitude': 22.7137,
            'languages': {'uk': 'Мукачево', 'en': 'Mukachevo', 'ru': 'Мукачево'},
        },
        {
            'name': 'Перечин',
            'latitude': 48.7403,
            'longitude': 22.4733,
            'languages': {'uk': 'Перечин', 'en': 'Perechyn', 'ru': 'Перечин'},
        },
        {
            'name': 'Рахів',
            'latitude': 48.0500,
            'longitude': 24.2000,
            'languages': {'uk': 'Рахів', 'en': 'Rakhiv', 'ru': 'Рахов'},
        },
        {
            'name': 'Свалява',
            'latitude': 48.5472,
            'longitude': 22.9864,
            'languages': {'uk': 'Свалява', 'en': 'Svalyava', 'ru': 'Свалява'},
        },
        {
            'name': 'Тячів',
            'latitude': 48.0161,
            'longitude': 23.5720,
            'languages': {'uk': 'Тячів', 'en': 'Tyachiv', 'ru': 'Тячев'},
        },
        {
            'name': 'Міжгір\'я',
            'latitude': 48.5374,
            'longitude': 23.2361,
            'languages': {'uk': 'Міжгір\'я', 'en': 'Mizhhirya', 'ru': 'Мижгирья'},
        },
        {
            'name': 'Порошково',
            'latitude': 48.2585,
            'longitude': 22.4240,
            'languages': {'uk': 'Порошково', 'en': 'Poroshkovo', 'ru': 'Порошково'},
        },
        {
            'name': 'Солотвино',
            'latitude': 48.3314,
            'longitude': 22.4672,
            'languages': {'uk': 'Солотвино', 'en': 'Solotvyno', 'ru': 'Солотвино'},
        },
        {
            'name': 'Ужгород',
            'latitude': 48.6240,
            'longitude': 22.2950,
            'languages': {'uk': 'Ужгород', 'en': 'Uzhhorod', 'ru': 'Ужгород'},
        },
        {
            'name': 'Хуст',
            'latitude': 48.1742,
            'longitude': 23.2897,
            'languages': {'uk': 'Хуст', 'en': 'Khust', 'ru': 'Хуст'},
        },
        {
            'name': 'Чоп',
            'latitude': 48.4308,
            'longitude': 22.2120,
            'languages': {'uk': 'Чоп', 'en': 'Chop', 'ru': 'Чоп'},
        },
    ],
    'Запорізька область': [
        {
            'name': 'Бердянськ',
            'latitude': 46.7597,
            'longitude': 36.7844,
            'languages': {'uk': 'Бердянськ', 'en': 'Berdyansk', 'ru': 'Бердянск'},
        },
        {
            'name': 'Василівка',
            'latitude': 47.4342,
            'longitude': 35.2765,
            'languages': {'uk': 'Василівка', 'en': 'Vasylivka', 'ru': 'Васильевка'},
        },
        {
            'name': 'Вільнянськ',
            'latitude': 47.9444,
            'longitude': 35.4331,
            'languages': {'uk': 'Вільнянськ', 'en': 'Vilniansk', 'ru': 'Вильнянск'},
        },
        {
            'name': 'Гуляйполе',
            'latitude': 47.6604,
            'longitude': 36.2817,
            'languages': {'uk': 'Гуляйполе', 'en': 'Hulyaipole', 'ru': 'Гуляйполе'},
        },
        {
            'name': 'Дніпрорудне',
            'latitude': 47.3822,
            'longitude': 34.9869,
            'languages': {'uk': 'Дніпрорудне', 'en': 'Dniprovydene', 'ru': 'Днепрорудное'},
        },
        {
            'name': 'Енергодар',
            'latitude': 47.4990,
            'longitude': 34.6561,
            'languages': {'uk': 'Енергодар', 'en': 'Enerhodar', 'ru': 'Энергодар'},
        },
        {
            'name': 'Запоріжжя',
            'latitude': 47.8378,
            'longitude': 35.1383,
            'languages': {'uk': 'Запоріжжя', 'en': 'Zaporizhzhia', 'ru': 'Запорожье'},
        },
        {
            'name': 'Кам\'янка-Дніпровська',
            'latitude': 47.4630,
            'longitude': 34.4228,
            'languages': {'uk': 'Кам\'янка-Дніпровська', 'en': 'Kamianka-Dniprovskaya', 'ru': 'Каменка-Днепровская'},
        },
        {
            'name': 'Мелітополь',
            'latitude': 46.8404,
            'longitude': 35.3590,
            'languages': {'uk': 'Мелітополь', 'en': 'Melitopol', 'ru': 'Мелитополь'},
        },
        {
            'name': 'Молочанськ',
            'latitude': 47.2044,
            'longitude': 35.5962,
            'languages': {'uk': 'Молочанськ', 'en': 'Molochansk', 'ru': 'Молочанск'},
        },
        {
            'name': 'Оріхів',
            'latitude': 47.5694,
            'longitude': 35.7778,
            'languages': {'uk': 'Оріхів', 'en': 'Orikhiv', 'ru': 'Орехов'},
        },
        {
            'name': 'Пологи',
            'latitude': 47.4756,
            'longitude': 36.2761,
            'languages': {'uk': 'Пологи', 'en': 'Pology', 'ru': 'Пологи'},
        },
        {
            'name': 'Приморськ',
            'latitude': 46.7189,
            'longitude': 36.3567,
            'languages': {'uk': 'Приморськ', 'en': 'Prymorśk', 'ru': 'Приморск'},
        },
        {
            'name': 'Токмак',
            'latitude': 47.2490,
            'longitude': 35.7031,
            'languages': {'uk': 'Токмак', 'en': 'Tokmak', 'ru': 'Токмак'},
        },
    ],
    'Івано-Франківська область': [
        {
            'name': 'Олехів',
            'latitude': 49.0669,
            'longitude': 23.8514,
            'languages': {'uk': 'Олехів', 'en': 'Olekhiv', 'ru': 'Олехов'},
        },
        {
            'name': 'Болехів',
            'latitude': 49.2600,
            'longitude': 24.6350,
            'languages': {'uk': 'Болехів', 'en': 'Bolekhiv', 'ru': 'Болехов'},
        },
        {
            'name': 'Бурштин',
            'latitude': 49.2600,
            'longitude': 24.6350,
            'languages': {'uk': 'Бурштин', 'en': 'Burshtyn', 'ru': 'Бурштин'},
        },
        {
            'name': 'Галич',
            'latitude': 49.1395,
            'longitude': 24.7317,
            'languages': {'uk': 'Галич', 'en': 'Halych', 'ru': 'Галич'},
        },
        {
            'name': 'Городенка',
            'latitude': 48.6675,
            'longitude': 25.5003,
            'languages': {'uk': 'Городенка', 'en': 'Horodenka', 'ru': 'Городенка'},
        },
        {
            'name': 'Долина',
            'latitude': 48.9808,
            'longitude': 24.0025,
            'languages': {'uk': 'Долина', 'en': 'Dolina', 'ru': 'Долина'},
        },
        {
            'name': 'Івано-Франківськ',
            'latitude': 48.9228,
            'longitude': 24.7106,
            'languages': {'uk': 'Івано-Франківськ', 'en': 'Ivano-Frankivsk', 'ru': 'Ивано-Франковск'},
        },
        {
            'name': 'Калуш',
            'latitude': 49.0442,
            'longitude': 24.3597,
            'languages': {'uk': 'Калуш', 'en': 'Kalush', 'ru': 'Калуш'},
        },
        {
            'name': 'Коломия',
            'latitude': 48.5417,
            'longitude': 25.0387,
            'languages': {'uk': 'Коломия', 'en': 'Kolomyia', 'ru': 'Коломыя'},
        },
        {
            'name': 'Косів',
            'latitude': 48.3142,
            'longitude': 25.0953,
            'languages': {'uk': 'Косів', 'en': 'Kosiv', 'ru': 'Косов'},
        },
        {
            'name': 'Надвірна',
            'latitude': 48.6303,
            'longitude': 24.5792,
            'languages': {'uk': 'Надвірна', 'en': 'Nadvirna', 'ru': 'Надворная'},
        },
        {
            'name': 'Рогатин',
            'latitude': 49.4122,
            'longitude': 24.6100,
            'languages': {'uk': 'Рогатин', 'en': 'Rohatyn', 'ru': 'Рогатин'},
        },
        {
            'name': 'Снятин',
            'latitude': 48.4511,
            'longitude': 25.5711,
            'languages': {'uk': 'Снятин', 'en': 'Snyatyn', 'ru': 'Снятын'},
        },
        {
            'name': 'Тисмениця',
            'latitude': 48.9020,
            'longitude': 24.8472,
            'languages': {'uk': 'Тисмениця', 'en': 'Tysmenytsia', 'ru': 'Тысменица'},
        },
        {
            'name': 'Тлумач',
            'latitude': 48.8556,
            'longitude': 24.9956,
            'languages': {'uk': 'Тлумач', 'en': 'Tlumach', 'ru': 'Тлумач'},
        },
        {
            'name': 'Яремче',
            'latitude': 48.4604,
            'longitude': 24.5585,
            'languages': {'uk': 'Яремче', 'en': 'Yaremche', 'ru': 'Яремче'},
        },
    ],
    'Київська область': [
        {
            'name': 'Боярка',
            'latitude': 50.2181,
            'longitude': 30.2813,
            'languages': {'uk': 'Боярка', 'en': 'Boyarka', 'ru': 'Боярка'},
        },
        {
            'name': 'Бровари',
            'latitude': 50.4542,
            'longitude': 30.7235,
            'languages': {'uk': 'Бровари', 'en': 'Brovari', 'ru': 'Бровары'},
        },
        {
            'name': 'Буча',
            'latitude': 50.5141,
            'longitude': 30.2181,
            'languages': {'uk': 'Буча', 'en': 'Bucha', 'ru': 'Буча'},
        },
        {
            'name': 'Вишневе',
            'latitude': 50.3750,
            'longitude': 30.4572,
            'languages': {'uk': 'Вишневе', 'en': 'Vyshneve', 'ru': 'Вишневое'},
        },
        {
            'name': 'Вишгород',
            'latitude': 50.5545,
            'longitude': 30.6663,
            'languages': {'uk': 'Вишгород', 'en': 'Vyshhorod', 'ru': 'Вышгород'},
        },
        {
            'name': 'Гостомель',
            'latitude': 50.5075,
            'longitude': 30.1790,
            'languages': {'uk': 'Гостомель', 'en': 'Hostomel', 'ru': 'Гостомель'},
        },
        {
            'name': 'Димер',
            'latitude': 50.5890,
            'longitude': 30.5993,
            'languages': {'uk': 'Димер', 'en': 'Dimer', 'ru': 'Димер'},
        },
        {
            'name': 'Ірпінь',
            'latitude': 50.5340,
            'longitude': 30.2366,
            'languages': {'uk': 'Ірпінь', 'en': 'Irpin', 'ru': 'Ирпень'},
        },
        {
            'name': 'Обухів',
            'latitude': 50.0957,
            'longitude': 30.6535,
            'languages': {'uk': 'Обухів', 'en': 'Obukhiv', 'ru': 'Обухов'},
        },
        {
            'name': 'Переяслав',
            'latitude': 49.7077,
            'longitude': 30.8939,
            'languages': {'uk': 'Переяслав', 'en': 'Pereiaslav', 'ru': 'Переяслав'},
        },
        {
            'name': 'Славутич',
            'latitude': 51.4980,
            'longitude': 30.1830,
            'languages': {'uk': 'Славутич', 'en': 'Slavutych', 'ru': 'Славутич'},
        },
        {
            'name': 'Тараща',
            'latitude': 49.6864,
            'longitude': 29.7786,
            'languages': {'uk': 'Тараща', 'en': 'Tarashcha', 'ru': 'Тараща'},
        },
        {
            'name': 'Фастів',
            'latitude': 50.0489,
            'longitude': 29.8930,
            'languages': {'uk': 'Фастів', 'en': 'Fastiv', 'ru': 'Фастов'},
        },
        {
            'name': 'Яготин',
            'latitude': 50.4540,
            'longitude': 30.6794,
            'languages': {'uk': 'Яготин', 'en': 'Yahotyn', 'ru': 'Яготин'},
        },
        {
            'name': 'Кагарлик',
            'latitude': 49.7939,
            'longitude': 30.6031,
            'languages': {'uk': 'Кагарлик', 'en': 'Kaharlyk', 'ru': 'Кагарлык'},
        },
        {
            'name': 'Ржищів',
            'latitude': 49.6437,
            'longitude': 30.8914,
            'languages': {'uk': 'Ржищів', 'en': 'Rzhyschiv', 'ru': 'Ржищев'},
        },
    ],
    'Кіровоградська область': [
        {
            'name': 'Благовіщенське',
            'latitude': 48.3300,
            'longitude': 30.2322,
            'languages': {'uk': 'Благовіщенське', 'en': 'Blahovishchenske', 'ru': 'Благовещенское'},
        },
        {
            'name': 'Бобринець',
            'latitude': 48.0578,
            'longitude': 32.1581,
            'languages': {'uk': 'Бобринець', 'en': 'Bobrynets', 'ru': 'Бобринец'},
        },
        {
            'name': 'Гайворон',
            'latitude': 48.3411,
            'longitude': 29.8606,
            'languages': {'uk': 'Гайворон', 'en': 'Haivoron', 'ru': 'Гайворон'},
        },
        {
            'name': 'Долинська',
            'latitude': 48.1108,
            'longitude': 32.7647,
            'languages': {'uk': 'Долинська', 'en': 'Dolynska', 'ru': 'Долинская'},
        },
        {
            'name': 'Знам\'янка',
            'latitude': 48.7137,
            'longitude': 32.6733,
            'languages': {'uk': 'Знам\'янка', 'en': 'Znamyanka', 'ru': 'Знаменка'},
        },
        {
            'name': 'Кропивницький',
            'latitude': 48.5100,
            'longitude': 32.2667,
            'languages': {'uk': 'Кропивницький', 'en': 'Kropyvnytskyi', 'ru': 'Кропивницкий'},
        },
        {
            'name': 'Мала Виска',
            'latitude': 48.6408,
            'longitude': 31.6272,
            'languages': {'uk': 'Мала Виска', 'en': 'Mala Vyska', 'ru': 'Мала Выска'},
        },
        {
            'name': 'Новомиргород',
            'latitude': 48.7808,
            'longitude': 31.6419,
            'languages': {'uk': 'Новомиргород', 'en': 'Novomyrhorod', 'ru': 'Новомиргород'},
        },
        {
            'name': 'Новоукраїнка',
            'latitude': 48.3160,
            'longitude': 31.5264,
            'languages': {'uk': 'Новоукраїнка', 'en': 'Novoukrainka', 'ru': 'Новоукраинка'},
        },
        {
            'name': 'Олександрія',
            'latitude': 48.6686,
            'longitude': 33.1075,
            'languages': {'uk': 'Олександрія', 'en': 'Oleksandriia', 'ru': 'Александрия'},
        },
        {
            'name': 'Помічна',
            'latitude': 48.2433,
            'longitude': 31.4061,
            'languages': {'uk': 'Помічна', 'en': 'Pomychnia', 'ru': 'Помощная'},
        },
        {
            'name': 'Світловодськ',
            'latitude': 49.0525,
            'longitude': 33.2050,
            'languages': {'uk': 'Світловодськ', 'en': 'Svitlovodsk', 'ru': 'Светловодск'},
        },
    ],
    'Луганська область': [
        {
            'name': 'Мазна',
            'latitude': 48.5217,
            'longitude': 38.5794,
            'languages': {'uk': 'Мазна', 'en': 'Mazna', 'ru': 'Мазна'},
        },
        {
            'name': 'Алмазна',
            'latitude': 48.5250,
            'longitude': 38.6344,
            'languages': {'uk': 'Алмазна', 'en': 'Almazna', 'ru': 'Алмазная'},
        },
        {
            'name': 'Алчевськ',
            'latitude': 48.4803,
            'longitude': 38.7961,
            'languages': {'uk': 'Алчевськ', 'en': 'Alchevsk', 'ru': 'Алчевск'},
        },
        {
            'name': 'Антрацит',
            'latitude': 48.4803,
            'longitude': 38.7961,
            'languages': {'uk': 'Антрацит', 'en': 'Antratsyt', 'ru': 'Антрацит'},
        },
        {
            'name': 'Боково-Хрустальне',
            'latitude': 48.4792,
            'longitude': 38.7894,
            'languages': {'uk': 'Боково-Хрустальне', 'en': 'Bokovo-Khrustalne', 'ru': 'Боково-Хрустальное'},
        },
        {
            'name': 'Брянка',
            'latitude': 48.4847,
            'longitude': 38.6778,
            'languages': {'uk': 'Брянка', 'en': 'Brianka', 'ru': 'Брянка'},
        },
        {
            'name': 'Вознесенівка',
            'latitude': 48.0714,
            'longitude': 39.7982,
            'languages': {'uk': 'Вознесенівка', 'en': 'Voznesenivka', 'ru': 'Вознесеновка'},
        },
        {
            'name': 'Гірське',
            'latitude': 48.7519,
            'longitude': 38.4950,
            'languages': {'uk': 'Гірське', 'en': 'Hirske', 'ru': 'Горское'},
        },
        {
            'name': 'Голубівка',
            'latitude': 48.6375,
            'longitude': 38.6433,
            'languages': {'uk': 'Голубівка', 'en': 'Holubivka', 'ru': 'Голубовка'},
        },
        {
            'name': 'Довжанськ',
            'latitude': 48.0583,
            'longitude': 39.6583,
            'languages': {'uk': 'Довжанськ', 'en': 'Dovzhansk', 'ru': 'Довжанск'},
        },
        {
            'name': 'Зимогір\'я',
            'latitude': 48.5911,
            'longitude': 38.9197,
            'languages': {'uk': 'Зимогір\'я', 'en': 'Zymohirya', 'ru': 'Зимогирья'},
        },
        {
            'name': 'Золоте',
            'latitude': 48.6928,
            'longitude': 38.5194,
            'languages': {'uk': 'Золоте', 'en': 'Zolote', 'ru': 'Золотое'},
        },
        {
            'name': 'Зоринськ',
            'latitude': 48.4145,
            'longitude': 38.6185,
            'languages': {'uk': 'Зоринськ', 'en': 'Zorynsk', 'ru': 'Зоринск'},
        },
        {
            'name': 'Ірміно',
            'latitude': 48.5967,
            'longitude': 38.5828,
            'languages': {'uk': 'Ірміно', 'en': 'Irmino', 'ru': 'Ирмино'},
        },
        {
            'name': 'Кадіївка',
            'latitude': 48.5680,
            'longitude': 38.6587,
            'languages': {'uk': 'Кадіївка', 'en': 'Kadiivka', 'ru': 'Кадиевка'},
        },
        {
            'name': 'Кипуче',
            'latitude': 48.4389,
            'longitude': 38.7175,
            'languages': {'uk': 'Кипуче', 'en': 'Kypuche', 'ru': 'Кипуче'},
        },
        {
            'name': 'Кремінна',
            'latitude': 49.0500,
            'longitude': 38.2211,
            'languages': {'uk': 'Кремінна', 'en': 'Kreminna', 'ru': 'Кременная'},
        },
        {
            'name': 'Лисичанськ',
            'latitude': 48.8899,
            'longitude': 38.4317,
            'languages': {'uk': 'Лисичанськ', 'en': 'Lysychansk', 'ru': 'Лисичанск'},
        },
        {
            'name': 'Луганськ',
            'latitude': 48.5685,
            'longitude': 39.3086,
            'languages': {'uk': 'Луганськ', 'en': 'Luhansk', 'ru': 'Луганск'},
        },
        {
            'name': 'Лутугине',
            'latitude': 48.4019,
            'longitude': 39.2103,
            'languages': {'uk': 'Лутугине', 'en': 'Lutuhyne', 'ru': 'Лутугино'},
        },
        {
            'name': 'Міусинськ',
            'latitude': 48.0725,
            'longitude': 38.9000,
            'languages': {'uk': 'Міусинськ', 'en': 'Miusynsk', 'ru': 'Миусинск'},
        },
        {
            'name': 'Новодружеськ',
            'latitude': 48.9667,
            'longitude': 38.3500,
            'languages': {'uk': 'Новодружеськ', 'en': 'Novodruzhesk', 'ru': 'Новодружеск'},
        },
        {
            'name': 'Олександрівськ',
            'latitude': 48.5798,
            'longitude': 39.1976,
            'languages': {'uk': 'Олександрівськ', 'en': 'Oleksandrivsk', 'ru': 'Александровск'},
        },
        {
            'name': 'Отаманівка',
            'latitude': 48.3444,
            'longitude': 39.6583,
            'languages': {'uk': 'Отаманівка', 'en': 'Otamanivka', 'ru': 'Отамановка'},
        },
        {
            'name': 'Перевальськ',
            'latitude': 48.4356,
            'longitude': 38.8172,
            'languages': {'uk': 'Перевальськ', 'en': 'Perevalsk', 'ru': 'Перевальск'},
        },
        {
            'name': 'Петрово-Красносілля',
            'latitude': 48.3000,
            'longitude': 38.8781,
            'languages': {'uk': 'Петрово-Красносілля', 'en': 'Petrovo-Krasnosillya', 'ru': 'Петрово-Красносилле'},
        },
        {
            'name': 'Попасна',
            'latitude': 48.6343,
            'longitude': 38.3800,
            'languages': {'uk': 'Попасна', 'en': 'Popasna', 'ru': 'Попасная'},
        },
        {
            'name': 'Привілля',
            'latitude': 48.9997,
            'longitude': 38.2947,
            'languages': {'uk': 'Привілля', 'en': 'Pryvillya', 'ru': 'Привиллия'},
        },
        {
            'name': 'Ровеньки',
            'latitude': 48.0712,
            'longitude': 39.3427,
            'languages': {'uk': 'Ровеньки', 'en': 'Rovenky', 'ru': 'Ровеньки'},
        },
        {
            'name': 'Рубіжне',
            'latitude': 49.0187,
            'longitude': 38.3817,
            'languages': {'uk': 'Рубіжне', 'en': 'Rubizhne', 'ru': 'Рубежное'},
        },
        {
            'name': 'Сватове',
            'latitude': 49.4092,
            'longitude': 38.1619,
            'languages': {'uk': 'Сватове', 'en': 'Svatove', 'ru': 'Сватово'},
        },
        {
            'name': 'Сіверськодонецьк',
            'latitude': 48.9565,
            'longitude': 38.4803,
            'languages': {'uk': 'Сіверськодонецьк', 'en': 'Severodonetsk', 'ru': 'Северодонецк'},
        },
        {
            'name': 'Сорокине',
            'latitude': 48.2992,
            'longitude': 39.7498,
            'languages': {'uk': 'Сорокине', 'en': 'Sorokyne', 'ru': 'Сорокино'},
        },
        {
            'name': 'Сокологірськ',
            'latitude': 48.6298,
            'longitude': 38.5620,
            'languages': {'uk': 'Сокологірськ', 'en': 'Sokolohirsk', 'ru': 'Сокологорск'},
        },
        {
            'name': 'Старобільськ',
            'latitude': 49.2833,
            'longitude': 38.9167,
            'languages': {'uk': 'Старобільськ', 'en': 'Starobilsk', 'ru': 'Старобельск'},
        },
        {
            'name': 'Суходільськ',
            'latitude': 48.3537,
            'longitude': 39.7217,
            'languages': {'uk': 'Суходільськ', 'en': 'Sukhodilsk', 'ru': 'Суходолск'},
        },
        {
            'name': 'Хрустальний',
            'latitude': 48.1272,
            'longitude': 38.9192,
            'languages': {'uk': 'Хрустальний', 'en': 'Khrustalnyi', 'ru': 'Хрустальный'},
        },
        {
            'name': 'Щастя',
            'latitude': 48.7382,
            'longitude': 39.2306,
            'languages': {'uk': 'Щастя', 'en': 'Shchastia', 'ru': 'Счастье'},
        },
    ],
    'Львівська область': [
        {
            'name': 'Белз',
            'latitude': 50.3800,
            'longitude': 24.0017,
            'languages': {'uk': 'Белз', 'en': 'Belz', 'ru': 'Белз'},
        },
        {
            'name': 'Бібрка',
            'latitude': 49.6358,
            'longitude': 24.2936,
            'languages': {'uk': 'Бібрка', 'en': 'Bibrka', 'ru': 'Бибрка'},
        },
        {
            'name': 'Борислав',
            'latitude': 49.2892,
            'longitude': 23.4189,
            'languages': {'uk': 'Борислав', 'en': 'Boryslav', 'ru': 'Борислав'},
        },
        {
            'name': 'Броди',
            'latitude': 50.0781,
            'longitude': 25.1542,
            'languages': {'uk': 'Броди', 'en': 'Brody', 'ru': 'Броды'},
        },
        {
            'name': 'Буськ',
            'latitude': 49.9683,
            'longitude': 24.6083,
            'languages': {'uk': 'Буськ', 'en': 'Busk', 'ru': 'Буск'},
        },
        {
            'name': 'Великі Мости',
            'latitude': 50.2400,
            'longitude': 24.1394,
            'languages': {'uk': 'Великі Мости', 'en': 'Velyki Mosty', 'ru': 'Великие Мосты'},
        },
        {
            'name': 'Винники',
            'latitude': 49.8156,
            'longitude': 24.1297,
            'languages': {'uk': 'Винники', 'en': 'Vynnyky', 'ru': 'Винники'},
        },
        {
            'name': 'Глиняни',
            'latitude': 49.8247,
            'longitude': 24.5161,
            'languages': {'uk': 'Глиняни', 'en': 'Hlyniany', 'ru': 'Глиняны'},
        },
        {
            'name': 'Городок',
            'latitude': 49.7854,
            'longitude': 23.6764,
            'languages': {'uk': 'Городок', 'en': 'Horodok', 'ru': 'Городок'},
        },
        {
            'name': 'Добромиль',
            'latitude': 49.5706,
            'longitude': 22.7895,
            'languages': {'uk': 'Добромиль', 'en': 'Dobromyl', 'ru': 'Добромиль'},
        },
        {
            'name': 'Дрогобич',
            'latitude': 49.3500,
            'longitude': 23.5000,
            'languages': {'uk': 'Дрогобич', 'en': 'Drohobych', 'ru': 'Дрогобыч'},
        },
        {
            'name': 'Дубляни',
            'latitude': 49.8961,
            'longitude': 24.0925,
            'languages': {'uk': 'Дубляни', 'en': 'Dublyany', 'ru': 'Дубляны'},
        },
        {
            'name': 'Жидачів',
            'latitude': 49.3850,
            'longitude': 24.1444,
            'languages': {'uk': 'Жидачів', 'en': 'Zhydachiv', 'ru': 'Жидачев'},
        },
        {
            'name': 'Жовква',
            'latitude': 50.0550,
            'longitude': 23.9760,
            'languages': {'uk': 'Жовква', 'en': 'Zhovkva', 'ru': 'Жолква'},
        },
        {
            'name': 'Золочів',
            'latitude': 49.8044,
            'longitude': 24.8903,
            'languages': {'uk': 'Золочів', 'en': 'Zolochiv', 'ru': 'Золочев'},
        },
        {
            'name': "Кам'янка-Бузька",
            'latitude': 50.1050,
            'longitude': 24.3377,
            'languages': {'uk': "Кам'янка-Бузька", 'en': 'Kamianka-Buzka', 'ru': 'Каменка-Бузька'},
        },
        {
            'name': 'Комарно',
            'latitude': 49.6306,
            'longitude': 23.6997,
            'languages': {'uk': 'Комарно', 'en': 'Komarno', 'ru': 'Комарно'},
        },
        {
            'name': 'Львів',
            'latitude': 49.8422,
            'longitude': 24.0316,
            'languages': {'uk': 'Львів', 'en': 'Lviv', 'ru': 'Львов'},
        },
        {
            'name': 'Миколаїв',
            'latitude': 49.5247,
            'longitude': 23.9789,
            'languages': {'uk': 'Миколаїв', 'en': 'Mykolaiv', 'ru': 'Николаев'},
        },
        {
            'name': 'Моршин',
            'latitude': 49.1547,
            'longitude': 23.8686,
            'languages': {'uk': 'Моршин', 'en': 'Morshyn', 'ru': 'Моршин'},
        },
        {
            'name': 'Мостиська',
            'latitude': 49.7917,
            'longitude': 23.1525,
            'languages': {'uk': 'Мостиська', 'en': 'Mostyska', 'ru': 'Мостиска'},
        },
        {
            'name': 'Новий Калинів',
            'latitude': 49.5606,
            'longitude': 23.3044,
            'languages': {'uk': 'Новий Калинів', 'en': 'Novyi Kalyniv', 'ru': 'Новый Калинов'},
        },
        {
            'name': 'Новий Розділ',
            'latitude': 49.4703,
            'longitude': 24.1347,
            'languages': {'uk': 'Новий Розділ', 'en': 'Novyi Rozdil', 'ru': 'Новый Раздел'},
        },
        {
            'name': 'Новояворівськ',
            'latitude': 49.9331,
            'longitude': 23.5712,
            'languages': {'uk': 'Новояворівськ', 'en': 'Novoyavorivsk', 'ru': 'Новояворовск'},
        },
        {
            'name': 'Перемишляни',
            'latitude': 49.6706,
            'longitude': 24.5567,
            'languages': {'uk': 'Перемишляни', 'en': 'Peremyshlyany', 'ru': 'Перемышляны'},
        },
        {
            'name': 'Пустомити',
            'latitude': 49.7200,
            'longitude': 23.8950,
            'languages': {'uk': 'Пустомити', 'en': 'Pustomyty', 'ru': 'Пустомиты'},
        },
        {
            'name': 'Рава-Руська',
            'latitude': 50.2242,
            'longitude': 23.6242,
            'languages': {'uk': 'Рава-Руська', 'en': 'Rava-Ruska', 'ru': 'Рава-Русская'},
        },
        {
            'name': 'Радехів',
            'latitude': 50.2770,
            'longitude': 24.6417,
            'languages': {'uk': 'Радехів', 'en': 'Radekhiv', 'ru': 'Радехов'},
        },
        {
            'name': 'Рудки',
            'latitude': 49.6530,
            'longitude': 23.4872,
            'languages': {'uk': 'Рудки', 'en': 'Rudky', 'ru': 'Рудки'},
        },
        {
            'name': 'Самбір',
            'latitude': 49.5167,
            'longitude': 23.2000,
            'languages': {'uk': 'Самбір', 'en': 'Sambir', 'ru': 'Самбор'},
        },
        {
            'name': 'Сколе',
            'latitude': 49.0389,
            'longitude': 23.5140,
            'languages': {'uk': 'Сколе', 'en': 'Skole', 'ru': 'Сколе'},
        },
        {
            'name': 'Сокаль',
            'latitude': 50.4800,
            'longitude': 24.2861,
            'languages': {'uk': 'Сокаль', 'en': 'Sokal', 'ru': 'Сокаль'},
        },
        {
            'name': 'Соснівка',
            'latitude': 49.7883,
            'longitude': 24.0617,
            'languages': {'uk': 'Соснівка', 'en': 'Sosnivka', 'ru': 'Сосновка'},
        },
        {
            'name': 'Старий Самбір',
            'latitude': 49.4414,
            'longitude': 23.0023,
            'languages': {'uk': 'Старий Самбір', 'en': 'Staryi Sambir', 'ru': 'Старый Самбор'},
        },
        {
            'name': 'Стебник',
            'latitude': 49.2962,
            'longitude': 23.5531,
            'languages': {'uk': 'Стебник', 'en': 'Stebnyk', 'ru': 'Стебник'},
        },
        {
            'name': 'Стрий',
            'latitude': 49.2562,
            'longitude': 23.8503,
            'languages': {'uk': 'Стрий', 'en': 'Stryi', 'ru': 'Стрый'},
        },
        {
            'name': 'Судова Вишня',
            'latitude': 49.9925,
            'longitude': 23.6164,
            'languages': {'uk': 'Судова Вишня', 'en': 'Sudova Vyshnia', 'ru': 'Судовая Вишня'},
        },
        {
            'name': 'Трускавець',
            'latitude': 49.2778,
            'longitude': 23.5078,
            'languages': {'uk': 'Трускавець', 'en': 'Truskavets', 'ru': 'Трускавец'},
        },
        {
            'name': 'Турка',
            'latitude': 49.1575,
            'longitude': 23.0225,
            'languages': {'uk': 'Турка', 'en': 'Turka', 'ru': 'Турка'},
        },
        {
            'name': 'Угнів',
            'latitude': 50.3682,
            'longitude': 23.7489,
            'languages': {'uk': 'Угнів', 'en': 'Uhniv', 'ru': 'Угнов'},
        },
        {
            'name': 'Хирів',
            'latitude': 49.5357,
            'longitude': 22.8545,
            'languages': {'uk': 'Хирів', 'en': 'Khyryv', 'ru': 'Хыров'},
        },
        {
            'name': 'Ходорів',
            'latitude': 49.4059,
            'longitude': 24.3104,
            'languages': {'uk': 'Ходорів', 'en': 'Khodoriv', 'ru': 'Ходоров'},
        },
        {
            'name': 'Червоноград',
            'latitude': 50.3867,
            'longitude': 24.2290,
            'languages': {'uk': 'Червоноград', 'en': 'Chervonohrad', 'ru': 'Червоноград'},
        },
        {
            'name': 'Яворів',
            'latitude': 49.9398,
            'longitude': 23.3858,
            'languages': {'uk': 'Яворів', 'en': 'Yavoriv', 'ru': 'Яворов'},
        },
    ],
    'Миколаївська область': [
        {
            'name': 'Баштанка',
            'latitude': 47.4028,
            'longitude': 32.4442,
            'languages': {'uk': 'Баштанка', 'en': 'BASHTANKA', 'ru': 'Баштанка'},
        },
        {
            'name': 'Вознесенськ',
            'latitude': 47.5725,
            'longitude': 31.3119,
            'languages': {'uk': 'Вознесенськ', 'en': 'Voznesensk', 'ru': 'Вознесенск'},
        },
        {
            'name': 'Миколаїв',
            'latitude': 46.9753,
            'longitude': 31.9937,
            'languages': {'uk': 'Миколаїв', 'en': 'Mykolaiv', 'ru': 'Николаев'},
        },
        {
            'name': 'Нова Одеса',
            'latitude': 47.2939,
            'longitude': 31.7889,
            'languages': {'uk': 'Нова Одеса', 'en': 'Nova Odesa', 'ru': 'Новая Одесса'},
        },
        {
            'name': 'Новий Буг',
            'latitude': 47.6840,
            'longitude': 32.5078,
            'languages': {'uk': 'Новий Буг', 'en': 'Novyi Buh', 'ru': 'Новый Буг'},
        },
        {
            'name': 'Очаків',
            'latitude': 46.6187,
            'longitude': 31.5392,
            'languages': {'uk': 'Очаків', 'en': 'Ochakiv', 'ru': 'Очаков'},
        },
        {
            'name': 'Первомайськ',
            'latitude': 48.0439,
            'longitude': 30.8500,
            'languages': {'uk': 'Первомайськ', 'en': 'Pervomaisk', 'ru': 'Первомайск'},
        },
        {
            'name': 'Снігурівка',
            'latitude': 47.1208,
            'longitude': 32.7997,
            'languages': {'uk': 'Снігурівка', 'en': 'Snihurivka', 'ru': 'Снегуревка'},
        },
        {
            'name': 'Южноукраїнськ',
            'latitude': 47.8217,
            'longitude': 31.1750,
            'languages': {'uk': 'Южноукраїнськ', 'en': 'Yuzhnoukrainsk', 'ru': 'Южноукраинск'},
        },
    ],
    'Одеська область': [
        {
            'name': 'Ананьїв',
            'latitude': 47.7228,
            'longitude': 29.9875,
            'languages': {'uk': 'Ананьїв', 'en': 'Ananiiv', 'ru': 'Ананьев'},
        },
        {
            'name': 'Арциз',
            'latitude': 45.9944,
            'longitude': 29.4322,
            'languages': {'uk': 'Арциз', 'en': 'Artsyz', 'ru': 'Арциз'},
        },
        {
            'name': 'Балта',
            'latitude': 47.9400,
            'longitude': 29.6219,
            'languages': {'uk': 'Балта', 'en': 'Balta', 'ru': 'Балта'},
        },
        {
            'name': 'Березівка',
            'latitude': 47.2006,
            'longitude': 30.9172,
            'languages': {'uk': 'Березівка', 'en': 'Berezivka', 'ru': 'Березовка'},
        },
        {
            'name': 'Білгород-Дністровський',
            'latitude': 46.1923,
            'longitude': 30.3333,
            'languages': {'uk': 'Білгород-Дністровський', 'en': 'Bilhorod-Dnistrovskyi', 'ru': 'Белгород-Днестровский'},
        },
        {
            'name': 'Біляївка',
            'latitude': 46.4826,
            'longitude': 30.2014,
            'languages': {'uk': 'Біляївка', 'en': 'Bilyaivka', 'ru': 'Биляевка'},
        },
        {
            'name': 'Болград',
            'latitude': 45.6673,
            'longitude': 28.6128,
            'languages': {'uk': 'Болград', 'en': 'Bolhrad', 'ru': 'Болград'},
        },
        {
            'name': 'Вилкове',
            'latitude': 45.3992,
            'longitude': 29.5937,
            'languages': {'uk': 'Вилкове', 'en': 'Vylkove', 'ru': 'Вилково'},
        },
        {
            'name': 'Ізмаїл',
            'latitude': 45.3511,
            'longitude': 28.8447,
            'languages': {'uk': 'Ізмаїл', 'en': 'Izmail', 'ru': 'Измаил'},
        },
        {
            'name': 'Кілія',
            'latitude': 45.4677,
            'longitude': 29.2378,
            'languages': {'uk': 'Кілія', 'en': 'Kiliya', 'ru': 'Килия'},
        },
        {
            'name': 'Кодима',
            'latitude': 48.0933,
            'longitude': 29.1250,
            'languages': {'uk': 'Кодима', 'en': 'Kodima', 'ru': 'Кодима'},
        },
        {
            'name': 'Одеса',
            'latitude': 46.4856,
            'longitude': 30.7433,
            'languages': {'uk': 'Одеса', 'en': 'Odesa', 'ru': 'Одесса'},
        },
        {
            'name': 'Подільськ',
            'latitude': 47.7420,
            'longitude': 29.5350,
            'languages': {'uk': 'Подільськ', 'en': 'Podyilsk', 'ru': 'Подольск'},
        },
        {
            'name': 'Рені',
            'latitude': 45.4575,
            'longitude': 28.2711,
            'languages': {'uk': 'Рені', 'en': 'Reni', 'ru': 'Рени'},
        },
        {
            'name': 'Роздільна',
            'latitude': 46.8520,
            'longitude': 30.0744,
            'languages': {'uk': 'Роздільна', 'en': 'Rozdilna', 'ru': 'Раздельная'},
        },
        {
            'name': 'Татарбунари',
            'latitude': 45.8469,
            'longitude': 29.6106,
            'languages': {'uk': 'Татарбунари', 'en': 'Tatarbunary', 'ru': 'Татарбунары'},
        },
        {
            'name': 'Теплодар',
            'latitude': 46.5037,
            'longitude': 30.3244,
            'languages': {'uk': 'Теплодар', 'en': 'Teplodar', 'ru': 'Теплодар'},
        },
        {
            'name': 'Чорноморськ',
            'latitude': 46.3017,
            'longitude': 30.6569,
            'languages': {'uk': 'Чорноморськ', 'en': 'Chornomorsk', 'ru': 'Черноморск'},
        },
        {
            'name': 'Южне',
            'latitude': 46.6237,
            'longitude': 31.1011,
            'languages': {'uk': 'Южне', 'en': 'Yuzhne', 'ru': 'Южное'},
        },
    ],
    'Полтавська область': [
        {
            'name': 'Полтава',
            'latitude': 49.5883,
            'longitude': 34.5510,
            'languages': {'uk': 'Полтава', 'en': 'Poltava', 'ru': 'Полтава'},
        },
        {
            'name': 'Кременчук',
            'latitude': 49.0752,
            'longitude': 33.4210,
            'languages': {'uk': 'Кременчук', 'en': 'Kremenchuk', 'ru': 'Кременчук'},
        },
        {
            'name': 'Лубни',
            'latitude': 49.6854,
            'longitude': 32.7857,
            'languages': {'uk': 'Лубни', 'en': 'Lubny', 'ru': 'Лубны'},
        },
        {
            'name': 'Миргород',
            'latitude': 49.9798,
            'longitude': 33.3750,
            'languages': {'uk': 'Миргород', 'en': 'Myrhorod', 'ru': 'Миргород'},
        },
        {
            'name': 'Гадяч',
            'latitude': 50.2298,
            'longitude': 33.5480,
            'languages': {'uk': 'Гадяч', 'en': 'Hadiach', 'ru': 'Гадяч'},
        },
        {
            'name': 'Пирятин',
            'latitude': 49.7118,
            'longitude': 33.5876,
            'languages': {'uk': 'Пирятин', 'en': 'Pyriatyn', 'ru': 'Пирятин'},
        },
        {
            'name': 'Зіньків',
            'latitude': 49.5567,
            'longitude': 34.0341,
            'languages': {'uk': 'Зіньків', 'en': 'Zinkiv', 'ru': 'Зиньков'},
        },
        {
            'name': 'Карлівка',
            'latitude': 49.5120,
            'longitude': 35.1938,
            'languages': {'uk': 'Карлівка', 'en': 'Karlivka', 'ru': 'Карловка'},
        },
        {
            'name': 'Кобеляки',
            'latitude': 49.3802,
            'longitude': 34.5464,
            'languages': {'uk': 'Кобеляки', 'en': 'Kobelyaky', 'ru': 'Кобеляки'},
        },
        {
            'name': 'Чутове',
            'latitude': 49.6404,
            'longitude': 34.7045,
            'languages': {'uk': 'Чутове', 'en': 'Chutove', 'ru': 'Чутово'},
        },
        {
            'name': 'Хорол',
            'latitude': 49.4538,
            'longitude': 33.6980,
            'languages': {'uk': 'Хорол', 'en': 'Khorol', 'ru': 'Хорол'},
        },
        {
            'name': 'Глобине',
            'latitude': 49.3064,
            'longitude': 33.5680,
            'languages': {'uk': 'Глобине', 'en': 'Hlobyn', 'ru': 'Глобино'},
        },
        {
            'name': 'Диканька',
            'latitude': 49.6539,
            'longitude': 34.5808,
            'languages': {'uk': 'Диканька', 'en': 'Dikanka', 'ru': 'Диканька'},
        },
        {
            'name': 'Щербані',
            'latitude': 49.5540,
            'longitude': 34.8375,
            'languages': {'uk': 'Щербані', 'en': 'Shcherbany', 'ru': 'Щербани'},
        },
        {
            'name': 'Ланні',
            'latitude': 49.1911,
            'longitude': 34.5765,
            'languages': {'uk': 'Ланні', 'en': 'Lanni', 'ru': 'Ланны'},
        },
        {
            'name': 'Нові Санжари',
            'latitude': 49.4993,
            'longitude': 34.4078,
            'languages': {'uk': 'Нові Санжари', 'en': 'Novi Sanzhary', 'ru': 'Новые Санжары'},
        },
        {
            'name': 'Семенівка',
            'latitude': 49.7742,
            'longitude': 34.4831,
            'languages': {'uk': 'Семенівка', 'en': 'Semenyivka', 'ru': 'Семеновка'},
        },
        {
            'name': 'Червонозаводське',
            'latitude': 49.5175,
            'longitude': 34.2203,
            'languages': {'uk': 'Червонозаводське', 'en': 'Chervonozavodske', 'ru': 'Червонозаводское'},
        },
        {
            'name': 'Тараща',
            'latitude': 49.3128,
            'longitude': 34.4117,
            'languages': {'uk': 'Тараща', 'en': 'Tarashcha', 'ru': 'Тараща'},
        },
    ],
    'Рівненська область': [
        {
            'name': 'Березне',
            'latitude': 51.0008,
            'longitude': 26.7508,
            'languages': {'uk': 'Березне', 'en': 'Berezne', 'ru': 'Березное'},
        },
        {
            'name': 'Вараш',
            'latitude': 51.3444,
            'longitude': 25.8508,
            'languages': {'uk': 'Вараш', 'en': 'Varash', 'ru': 'Вараш'},
        },
        {
            'name': 'Дубно',
            'latitude': 50.3931,
            'longitude': 25.7350,
            'languages': {'uk': 'Дубно', 'en': 'Dubno', 'ru': 'Дубно'},
        },
        {
            'name': 'Дубровиця',
            'latitude': 51.5742,
            'longitude': 26.5650,
            'languages': {'uk': 'Дубровиця', 'en': 'Dubrovitsa', 'ru': 'Дубровица'},
        },
        {
            'name': 'Здолбунів',
            'latitude': 50.5095,
            'longitude': 26.2597,
            'languages': {'uk': 'Здолбунів', 'en': 'Zdolbuniv', 'ru': 'Здолбунов'},
        },
        {
            'name': 'Корець',
            'latitude': 50.6172,
            'longitude': 27.1608,
            'languages': {'uk': 'Корець', 'en': 'Korets', 'ru': 'Корец'},
        },
        {
            'name': 'Костопіль',
            'latitude': 50.8833,
            'longitude': 26.4431,
            'languages': {'uk': 'Костопіль', 'en': 'Kostopil', 'ru': 'Костополь'},
        },
        {
            'name': 'Острог',
            'latitude': 50.3292,
            'longitude': 26.5139,
            'languages': {'uk': 'Острог', 'en': 'Ostroh', 'ru': 'Острог'},
        },
        {
            'name': 'Радивилів',
            'latitude': 50.1287,
            'longitude': 25.2644,
            'languages': {'uk': 'Радивилів', 'en': 'Radyvyliv', 'ru': 'Радивилов'},
        },
        {
            'name': 'Рівне',
            'latitude': 50.6198,
            'longitude': 26.2515,
            'languages': {'uk': 'Рівне', 'en': 'Rivne', 'ru': 'Ровно'},
        },
        {
            'name': 'Сарни',
            'latitude': 51.3270,
            'longitude': 26.6331,
            'languages': {'uk': 'Сарни', 'en': 'Sarny', 'ru': 'Сарны'},
        },
    ],
    'Сумська область': [
        {
            'name': 'Суми',
            'latitude': 50.9071,
            'longitude': 34.7983,
            'languages': {'uk': 'Суми', 'en': 'Sumy', 'ru': 'Сумы'},
        },
        {
            'name': 'Охтирка',
            'latitude': 50.5864,
            'longitude': 34.8672,
            'languages': {'uk': 'Охтирка', 'en': 'Okhtyrka', 'ru': 'Охтырка'},
        },
        {
            'name': 'Конотоп',
            'latitude': 50.9050,
            'longitude': 32.4223,
            'languages': {'uk': 'Конотоп', 'en': 'Konotop', 'ru': 'Конотоп'},
        },
        {
            'name': 'Шостка',
            'latitude': 51.3082,
            'longitude': 34.2460,
            'languages': {'uk': 'Шостка', 'en': 'Shostka', 'ru': 'Шостка'},
        },
        {
            'name': 'Ромни',
            'latitude': 50.7278,
            'longitude': 33.5836,
            'languages': {'uk': 'Ромни', 'en': 'Romny', 'ru': 'Ромны'},
        },
        {
            'name': 'Середина-Буда',
            'latitude': 50.4872,
            'longitude': 34.3258,
            'languages': {'uk': 'Середина-Буда', 'en': 'Seredyne-Buda', 'ru': 'Середина-Буда'},
        },
        {
            'name': 'Тростянець',
            'latitude': 50.7716,
            'longitude': 34.3744,
            'languages': {'uk': 'Тростянець', 'en': 'Trostianets', 'ru': 'Тростянец'},
        },
        {
            'name': 'Лебедин',
            'latitude': 50.5173,
            'longitude': 34.3498,
            'languages': {'uk': 'Лебедин', 'en': 'Lebedyn', 'ru': 'Лебедин'},
        },
        {
            'name': 'Кролевець',
            'latitude': 51.2121,
            'longitude': 33.3955,
            'languages': {'uk': 'Кролевець', 'en': 'Krolevets', 'ru': 'Кролевец'},
        },
        {
            'name': 'Білопілля',
            'latitude': 50.8195,
            'longitude': 34.8453,
            'languages': {'uk': 'Білопілля', 'en': 'Bilopillya', 'ru': 'Белополье'},
        },
        {
            'name': 'Глухів',
            'latitude': 50.7491,
            'longitude': 33.5984,
            'languages': {'uk': 'Глухів', 'en': 'Hlukhiv', 'ru': 'Глухов'},
        },
        {
            'name': 'Недригайлів',
            'latitude': 50.4690,
            'longitude': 33.5227,
            'languages': {'uk': 'Недригайлів', 'en': 'Nedryhailiv', 'ru': 'Недригайлов'},
        },
        {
            'name': 'Ворожба',
            'latitude': 50.6969,
            'longitude': 34.8432,
            'languages': {'uk': 'Ворожба', 'en': 'Vorożba', 'ru': 'Ворожба'},
        },
        {
            'name': 'Путивль',
            'latitude': 50.5342,
            'longitude': 34.6428,
            'languages': {'uk': 'Путивль', 'en': 'Putivl', 'ru': 'Путивль'},
        },
        {
            'name': 'Ямпіль',
            'latitude': 50.4732,
            'longitude': 34.5580,
            'languages': {'uk': 'Ямпіль', 'en': 'Yampil', 'ru': 'Ямполь'},
        },
    ],
    'Тернопільська область': [
        {
            'name': 'Бережани',
            'latitude': 49.4464,
            'longitude': 24.9436,
            'languages': {'uk': 'Бережани', 'en': 'Berezany', 'ru': 'Бережаны'},
        },
        {
            'name': 'Борщів',
            'latitude': 48.8022,
            'longitude': 26.0400,
            'languages': {'uk': 'Борщів', 'en': 'Borshchiv', 'ru': 'Борщев'},
        },
        {
            'name': 'Бучач',
            'latitude': 49.0628,
            'longitude': 25.3795,
            'languages': {'uk': 'Бучач', 'en': 'Buchach', 'ru': 'Бучач'},
        },
        {
            'name': 'Заліщики',
            'latitude': 48.6500,
            'longitude': 25.7367,
            'languages': {'uk': 'Заліщики', 'en': 'Zalishchyky', 'ru': 'Залещики'},
        },
        {
            'name': 'Збараж',
            'latitude': 49.6715,
            'longitude': 25.7708,
            'languages': {'uk': 'Збараж', 'en': 'Zbarazh', 'ru': 'Збараж'},
        },
        {
            'name': 'Зборів',
            'latitude': 49.6617,
            'longitude': 25.1453,
            'languages': {'uk': 'Зборів', 'en': 'Zboriv', 'ru': 'Зборов'},
        },
        {
            'name': 'Копичинці',
            'latitude': 49.1081,
            'longitude': 25.9128,
            'languages': {'uk': 'Копичинці', 'en': 'Kopychyntsi', 'ru': 'Копычинцы'},
        },
        {
            'name': 'Кременець',
            'latitude': 50.1081,
            'longitude': 25.7275,
            'languages': {'uk': 'Кременець', 'en': 'Kremenets', 'ru': 'Кременец'},
        },
        {
            'name': 'Ланівці',
            'latitude': 49.8667,
            'longitude': 26.0872,
            'languages': {'uk': 'Ланівці', 'en': 'Lanivtsi', 'ru': 'Ланивцы'},
        },
        {
            'name': 'Монастириська',
            'latitude': 49.0884,
            'longitude': 25.1667,
            'languages': {'uk': 'Монастириська', 'en': 'Monastyryshche', 'ru': 'Монастырщина'},
        },
        {
            'name': 'Підгайці',
            'latitude': 49.2750,
            'longitude': 25.1342,
            'languages': {'uk': 'Підгайці', 'en': 'Pidhaitsi', 'ru': 'Подгайцы'},
        },
        {
            'name': 'Почаїв',
            'latitude': 50.0065,
            'longitude': 25.5104,
            'languages': {'uk': 'Почаїв', 'en': 'Pochayiv', 'ru': 'Почаев'},
        },
        {
            'name': 'Скалат',
            'latitude': 49.4290,
            'longitude': 25.9744,
            'languages': {'uk': 'Скалат', 'en': 'Skalat', 'ru': 'Скалат'},
        },
        {
            'name': 'Теребовля',
            'latitude': 49.3006,
            'longitude': 25.6995,
            'languages': {'uk': 'Теребовля', 'en': 'Terebovlia', 'ru': 'Теребовля'},
        },
        {
            'name': 'Тернопіль',
            'latitude': 49.5560,
            'longitude': 25.6056,
            'languages': {'uk': 'Тернопіль', 'en': 'Ternopil', 'ru': 'Тернополь'},
        },
        {
            'name': 'Хоростків',
            'latitude': 49.2094,
            'longitude': 25.9175,
            'languages': {'uk': 'Хоростків', 'en': 'Khorostkiv', 'ru': 'Хоростков'},
        },
        {
            'name': 'Чортків',
            'latitude': 49.0070,
            'longitude': 25.7875,
            'languages': {'uk': 'Чортків', 'en': 'Chortkiv', 'ru': 'Чортков'},
        },
        {
            'name': 'Шумськ',
            'latitude': 50.1142,
            'longitude': 26.1130,
            'languages': {'uk': 'Шумськ', 'en': 'Shumsk', 'ru': 'Шумск'},
        },
    ],
    'Харківська область': [
        {
            'name': 'Балаклія',
            'latitude': 49.4592,
            'longitude': 36.8525,
            'languages': {'uk': 'Балаклія', 'en': 'Balakliya', 'ru': 'Балаклея'},
        },
        {
            'name': 'Барвінкове',
            'latitude': 48.9100,
            'longitude': 37.0231,
            'languages': {'uk': 'Барвінкове', 'en': 'Barvinkove', 'ru': 'Барвенково'},
        },
        {
            'name': 'Богодухів',
            'latitude': 50.1617,
            'longitude': 35.5256,
            'languages': {'uk': 'Богодухів', 'en': 'Bohodukhiv', 'ru': 'Богодухов'},
        },
        {
            'name': 'Валки',
            'latitude': 49.8382,
            'longitude': 35.6172,
            'languages': {'uk': 'Валки', 'en': 'Valky', 'ru': 'Валки'},
        },
        {
            'name': 'Вовчанськ',
            'latitude': 50.2879,
            'longitude': 36.9434,
            'languages': {'uk': 'Вовчанськ', 'en': 'Vovchansk', 'ru': 'Вовчанск'},
        },
        {
            'name': 'Дергачі',
            'latitude': 50.1115,
            'longitude': 36.1217,
            'languages': {'uk': 'Дергачі', 'en': 'Derhachi', 'ru': 'Дергачи'},
        },
        {
            'name': 'Зміїв',
            'latitude': 49.6878,
            'longitude': 36.3534,
            'languages': {'uk': 'Зміїв', 'en': 'Zmiiv', 'ru': 'Змиев'},
        },
        {
            'name': 'Ізюм',
            'latitude': 49.1959,
            'longitude': 37.2797,
            'languages': {'uk': 'Ізюм', 'en': 'Izyum', 'ru': 'Изюм'},
        },
        {
            'name': 'Красноград',
            'latitude': 49.3717,
            'longitude': 35.4560,
            'languages': {'uk': 'Красноград', 'en': 'Krasnohrad', 'ru': 'Красноград'},
        },
        {
            'name': 'Куп\'янськ',
            'latitude': 49.7064,
            'longitude': 37.6000,
            'languages': {'uk': 'Куп\'янськ', 'en': 'Kupiansk', 'ru': 'Купянск'},
        },
        {
            'name': 'Лозова',
            'latitude': 48.8892,
            'longitude': 36.3160,
            'languages': {'uk': 'Лозова', 'en': 'Lozova', 'ru': 'Лозовая'},
        },
        {
            'name': 'Люботин',
            'latitude': 49.9483,
            'longitude': 35.9295,
            'languages': {'uk': 'Люботин', 'en': 'Lyubotyn', 'ru': 'Люботин'},
        },
        {
            'name': 'Мерефа',
            'latitude': 49.8186,
            'longitude': 36.0683,
            'languages': {'uk': 'Мерефа', 'en': 'Merafa', 'ru': 'Мерефа'},
        },
        {
            'name': 'Первомайський',
            'latitude': 49.3867,
            'longitude': 36.2132,
            'languages': {'uk': 'Первомайський', 'en': 'Pervomaiskyi', 'ru': 'Первомайский'},
        },
        {
            'name': 'Південне',
            'latitude': 49.8767,
            'longitude': 36.0645,
            'languages': {'uk': 'Південне', 'en': 'Pivdenne', 'ru': 'Южное'},
        },
        {
            'name': 'Харків',
            'latitude': 50.0024,
            'longitude': 36.2296,
            'languages': {'uk': 'Харків', 'en': 'Kharkiv', 'ru': 'Харьков'},
        },
        {
            'name': 'Чугуїв',
            'latitude': 49.8265,
            'longitude': 36.6805,
            'languages': {'uk': 'Чугуїв', 'en': 'Chuhuiv', 'ru': 'Чугуев'},
        },
    ],
    'Херсонська область': [
        {
            'name': 'Берислав',
            'latitude': 46.8414,
            'longitude': 33.4295,
            'languages': {'uk': 'Берислав', 'en': 'Berislav', 'ru': 'Берислав'},
        },
        {
            'name': 'Генічеськ',
            'latitude': 46.1760,
            'longitude': 34.7990,
            'languages': {'uk': 'Генічеськ', 'en': 'Henichesk', 'ru': 'Геническ'},
        },
        {
            'name': 'Гола Пристань',
            'latitude': 46.5230,
            'longitude': 32.5158,
            'languages': {'uk': 'Гола Пристань', 'en': 'Hola Prystan', 'ru': 'Голая Пристань'},
        },
        {
            'name': 'Каховка',
            'latitude': 46.7979,
            'longitude': 33.4750,
            'languages': {'uk': 'Каховка', 'en': 'Kakhovka', 'ru': 'Каховка'},
        },
        {
            'name': 'Нова Каховка',
            'latitude': 46.7512,
            'longitude': 33.3606,
            'languages': {'uk': 'Нова Каховка', 'en': 'Nova Kakhovka', 'ru': 'Новая Каховка'},
        },
        {
            'name': 'Олешки',
            'latitude': 46.6174,
            'longitude': 32.7274,
            'languages': {'uk': 'Олешки', 'en': 'Oleshky', 'ru': 'Олешки'},
        },
        {
            'name': 'Скадовськ',
            'latitude': 46.1174,
            'longitude': 32.9180,
            'languages': {'uk': 'Скадовськ', 'en': 'Skadovsk', 'ru': 'Скадовск'},
        },
        {
            'name': 'Таврійськ',
            'latitude': 46.7534,
            'longitude': 33.4200,
            'languages': {'uk': 'Таврійськ', 'en': 'Tavriysk', 'ru': 'Таврийск'},
        },
        {
            'name': 'Херсон',
            'latitude': 46.6400,
            'longitude': 32.6144,
            'languages': {'uk': 'Херсон', 'en': 'Kherson', 'ru': 'Херсон'},
        },
    ],
    'Хмельницька область': [
        {
            'name': 'Волочиськ',
            'latitude': 49.5378,
            'longitude': 26.2006,
            'languages': {'uk': 'Волочиськ', 'en': 'Volochysk', 'ru': 'Волочиск'},
        },
        {
            'name': 'Городок',
            'latitude': 49.1669,
            'longitude': 26.5817,
            'languages': {'uk': 'Городок', 'en': 'Horodok', 'ru': 'Городок'},
        },
        {
            'name': 'Деражня',
            'latitude': 49.2704,
            'longitude': 27.4381,
            'languages': {'uk': 'Деражня', 'en': 'Derazhnya', 'ru': 'Деражня'},
        },
        {
            'name': 'Дунаївці',
            'latitude': 48.8894,
            'longitude': 26.8569,
            'languages': {'uk': 'Дунаївці', 'en': 'Dunaivtsi', 'ru': 'Дунаевцы'},
        },
        {
            'name': 'Ізяслав',
            'latitude': 50.1189,
            'longitude': 26.8214,
            'languages': {'uk': 'Ізяслав', 'en': 'Iziaslav', 'ru': 'Изясллав'},
        },
        {
            'name': 'Кам\'янець-Подільський',
            'latitude': 48.6806,
            'longitude': 26.5806,
            'languages': {'uk': 'Кам\'янець-Подільський', 'en': 'Kamianets-Podilskyi', 'ru': 'Каменец-Подольский'},
        },
        {
            'name': 'Красилів',
            'latitude': 49.6508,
            'longitude': 26.9667,
            'languages': {'uk': 'Красилів', 'en': 'Krasyliv', 'ru': 'Красилов'},
        },
        {
            'name': 'Нетішин',
            'latitude': 50.3300,
            'longitude': 26.6400,
            'languages': {'uk': 'Нетішин', 'en': 'Netishyn', 'ru': 'Нетишин'},
        },
        {
            'name': 'Полонне',
            'latitude': 50.1250,
            'longitude': 27.5072,
            'languages': {'uk': 'Полонне', 'en': 'Polonne', 'ru': 'Полонное'},
        },
        {
            'name': 'Славута',
            'latitude': 50.2950,
            'longitude': 26.8589,
            'languages': {'uk': 'Славута', 'en': 'Slavuta', 'ru': 'Славута'},
        },
        {
            'name': 'Старокостянтинів',
            'latitude': 49.7539,
            'longitude': 27.2203,
            'languages': {'uk': 'Старокостянтинів', 'en': 'Starkostiantyniv', 'ru': 'Староконстантинов'},
        },
        {
            'name': 'Хмельницький',
            'latitude': 49.4195,
            'longitude': 26.9795,
            'languages': {'uk': 'Хмельницький', 'en': 'Khmelnytskyi', 'ru': 'Хмельницкий'},
        },
        {
            'name': 'Шепетівка',
            'latitude': 50.1787,
            'longitude': 27.0600,
            'languages': {'uk': 'Шепетівка', 'en': 'Shepetivka', 'ru': 'Шепетовка'},
        },
    ],
    'Черкаська область': [
        {
            'name': 'Ватутіне',
            'latitude': 49.0119,
            'longitude': 31.0715,
            'languages': {'uk': 'Ватутіне', 'en': 'Vatutine', 'ru': 'Ватутин'},
        },
        {
            'name': 'Городище',
            'latitude': 49.2925,
            'longitude': 31.4580,
            'languages': {'uk': 'Городище', 'en': 'Horodyshche', 'ru': 'Городище'},
        },
        {
            'name': 'Жашків',
            'latitude': 49.2360,
            'longitude': 30.1100,
            'languages': {'uk': 'Жашків', 'en': 'Zhashkiv', 'ru': 'Жашков'},
        },
        {
            'name': 'Звенигородка',
            'latitude': 49.0698,
            'longitude': 30.9673,
            'languages': {'uk': 'Звенигородка', 'en': 'Zvenyhorodka', 'ru': 'Звенигородка'},
        },
        {
            'name': 'Золотоноша',
            'latitude': 49.6689,
            'longitude': 32.0477,
            'languages': {'uk': 'Золотоноша', 'en': 'Zolotonosha', 'ru': 'Золотоноша'},
        },
        {
            'name': 'Кам\'янка',
            'latitude': 49.0312,
            'longitude': 32.0976,
            'languages': {'uk': 'Кам\'янка', 'en': 'Kamyanka', 'ru': 'Камень'},
        },
        {
            'name': 'Канів',
            'latitude': 49.7448,
            'longitude': 31.4558,
            'languages': {'uk': 'Канів', 'en': 'Kaniv', 'ru': 'Канев'},
        },
        {
            'name': 'Корсунь-Шевченківський',
            'latitude': 49.4195,
            'longitude': 31.2772,
            'languages': {
                'uk': 'Корсунь-Шевченківський',
                'en': 'Korsun-Shevchenkivskyi',
                'ru': 'Корсунь-Шевченковский',
            },
        },
        {
            'name': 'Монастирище',
            'latitude': 48.9900,
            'longitude': 31.2772,
            'languages': {'uk': 'Монастирище', 'en': 'Monastyrishche', 'ru': 'Монастырщина'},
        },
        {
            'name': 'Сміла',
            'latitude': 49.2115,
            'longitude': 31.8732,
            'languages': {'uk': 'Сміла', 'en': 'Smila', 'ru': 'Смела'},
        },
        {
            'name': 'Тальне',
            'latitude': 48.8861,
            'longitude': 30.7025,
            'languages': {'uk': 'Тальне', 'en': 'Talne', 'ru': 'Тальное'},
        },
        {
            'name': 'Умань',
            'latitude': 48.7500,
            'longitude': 30.2194,
            'languages': {'uk': 'Умань', 'en': 'Uman', 'ru': 'Умань'},
        },
        {
            'name': 'Христинівка',
            'latitude': 48.8147,
            'longitude': 29.9684,
            'languages': {'uk': 'Христинівка', 'en': 'Khrystynivka', 'ru': 'Христиновка'},
        },
        {
            'name': 'Черкаси',
            'latitude': 49.4444,
            'longitude': 32.0608,
            'languages': {'uk': 'Черкаси', 'en': 'Cherkasy', 'ru': 'Черкассы'},
        },
        {
            'name': 'Чигирин',
            'latitude': 49.0772,
            'longitude': 32.6492,
            'languages': {'uk': 'Чигирин', 'en': 'Chyhyryn', 'ru': 'Чигирин'},
        },
        {
            'name': 'Шпола',
            'latitude': 48.8153,
            'longitude': 29.9684,
            'languages': {'uk': 'Шпола', 'en': 'Shpola', 'ru': 'Шпола'},
        },
    ],
    'Чернівецька область': [
        {
            'name': 'Вашківці',
            'latitude': 48.3753,
            'longitude': 25.4978,
            'languages': {'uk': 'Вашківці', 'en': 'Vashkivtsi', 'ru': 'Вашковцы'},
        },
        {
            'name': 'Вижниця',
            'latitude': 48.2453,
            'longitude': 25.1822,
            'languages': {'uk': 'Вижниця', 'en': 'Vyzhnytsia', 'ru': 'Вижница'},
        },
        {
            'name': 'Герца',
            'latitude': 48.1467,
            'longitude': 26.2583,
            'languages': {'uk': 'Герца', 'en': 'Hertsa', 'ru': 'Герца'},
        },
        {
            'name': 'Заставна',
            'latitude': 48.5203,
            'longitude': 25.8450,
            'languages': {'uk': 'Заставна', 'en': 'Zastavna', 'ru': 'Заставна'},
        },
        {
            'name': 'Кіцмань',
            'latitude': 48.4411,
            'longitude': 25.7669,
            'languages': {'uk': 'Кіцмань', 'en': 'Kitsman', 'ru': 'Кицмань'},
        },
        {
            'name': 'Новодністровськ',
            'latitude': 48.5822,
            'longitude': 27.4369,
            'languages': {'uk': 'Новодністровськ', 'en': 'Novodnistrovsk', 'ru': 'Новоднестровск'},
        },
        {
            'name': 'Новоселиця',
            'latitude': 48.2192,
            'longitude': 26.2653,
            'languages': {'uk': 'Новоселиця', 'en': 'Novoselitsa', 'ru': 'Новоселица'},
        },
        {
            'name': 'Сокиряни',
            'latitude': 48.4532,
            'longitude': 27.4161,
            'languages': {'uk': 'Сокиряни', 'en': 'Sokyryany', 'ru': 'Сокиряны'},
        },
        {
            'name': 'Сторожинець',
            'latitude': 48.1597,
            'longitude': 25.7144,
            'languages': {'uk': 'Сторожинець', 'en': 'Storozhynets', 'ru': 'Сторожинец'},
        },
        {
            'name': 'Хотин',
            'latitude': 48.5094,
            'longitude': 26.4919,
            'languages': {'uk': 'Хотин', 'en': 'Khotyn', 'ru': 'Хотин'},
        },
        {
            'name': 'Чернівці',
            'latitude': 48.2908,
            'longitude': 25.9344,
            'languages': {'uk': 'Чернівці', 'en': 'Chernivtsi', 'ru': 'Черновцы'},
        },
    ],
    'Чернігівська область': [
        {
            'name': 'Батурин',
            'latitude': 51.3387,
            'longitude': 32.8772,
            'languages': {'uk': 'Батурин', 'en': 'Baturyn', 'ru': 'Батурин'},
        },
        {
            'name': 'Бахмач',
            'latitude': 51.1756,
            'longitude': 32.8272,
            'languages': {'uk': 'Бахмач', 'en': 'Bakhmach', 'ru': 'Бахмач'},
        },
        {
            'name': 'Бобровиця',
            'latitude': 50.7500,
            'longitude': 31.3864,
            'languages': {'uk': 'Бобровиця', 'en': 'Bobrovytsia', 'ru': 'Бобровица'},
        },
        {
            'name': 'Борзна',
            'latitude': 51.2531,
            'longitude': 32.4292,
            'languages': {'uk': 'Борзна', 'en': 'Borzna', 'ru': 'Борзна'},
        },
        {
            'name': 'Городня',
            'latitude': 51.8931,
            'longitude': 31.5947,
            'languages': {'uk': 'Городня', 'en': 'Horodnia', 'ru': 'Городня'},
        },
        {
            'name': 'Ічня',
            'latitude': 50.8561,
            'longitude': 32.3772,
            'languages': {'uk': 'Ічня', 'en': 'Ichniya', 'ru': 'Ичня'},
        },
        {
            'name': 'Корюківка',
            'latitude': 51.7730,
            'longitude': 32.2731,
            'languages': {'uk': 'Корюківка', 'en': 'Koryukivka', 'ru': 'Корюковка'},
        },
        {
            'name': 'Мена',
            'latitude': 51.5242,
            'longitude': 32.2211,
            'languages': {'uk': 'Мена', 'en': 'Mena', 'ru': 'Мена'},
        },
        {
            'name': 'Ніжин',
            'latitude': 51.0428,
            'longitude': 31.8737,
            'languages': {'uk': 'Ніжин', 'en': 'Nizhyn', 'ru': 'Нежин'},
        },
        {
            'name': 'Новгород-Сіверський',
            'latitude': 52.0087,
            'longitude': 33.2736,
            'languages': {'uk': 'Новгород-Сіверський', 'en': 'Novhorod-Siverskyi', 'ru': 'Новгород-Северский'},
        },
        {
            'name': 'Носівка',
            'latitude': 50.9300,
            'longitude': 31.5800,
            'languages': {'uk': 'Носівка', 'en': 'Nosivka', 'ru': 'Носовка'},
        },
        {
            'name': 'Остер',
            'latitude': 50.9487,
            'longitude': 30.8811,
            'languages': {'uk': 'Остер', 'en': 'Oster', 'ru': 'Остр'},
        },
        {
            'name': 'Прилуки',
            'latitude': 50.5892,
            'longitude': 32.3856,
            'languages': {'uk': 'Прилуки', 'en': 'Pryluky', 'ru': 'Прилуки'},
        },
        {
            'name': 'Семенівка',
            'latitude': 52.1730,
            'longitude': 32.5922,
            'languages': {'uk': 'Семенівка', 'en': 'Semenivka', 'ru': 'Семеновка'},
        },
        {
            'name': 'Сновськ',
            'latitude': 51.8203,
            'longitude': 31.9508,
            'languages': {'uk': 'Сновськ', 'en': 'Snovsk', 'ru': 'Сновск'},
        },
        {
            'name': 'Чернігів',
            'latitude': 51.4911,
            'longitude': 31.2987,
            'languages': {'uk': 'Чернігів', 'en': 'Chernihiv', 'ru': 'Чернигов'},
        },
    ],
    'Місто Київ': [
        {
            'name': 'Київ',
            'latitude': 50.4501,
            'longitude': 30.5234,
            'languages': {'uk': 'Київ', 'en': 'Kyiv', 'ru': 'Киев'},
        },
    ],
    'Місто Севастополь': [
        {
            'name': 'Севастополь',
            'latitude': 44.6167,
            'longitude': 33.5258,
            'languages': {'uk': 'Севастополь', 'en': 'Sevastopol', 'ru': 'Севастополь'},
        },
    ],
}
